import type { EquipmentFilter, Facility, TypeFilter } from "./types";

// 実在するトリッキング/パルクール/アクロバット練習施設。
// 名称・住所・エリア・座標・公式リンクは実データ。営業時間・器具・レッスン等は
// 公式サイトに記載のある施設のみ収録（出典の無い項目は未掲載）。
// 距離(distance)は東京駅を基準点とした概算値。写真は準備中のプレースホルダー。
export const FACILITIES: Facility[] = [
  {
    id: "f01",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    openedAt: "2018年",
    name: "MISSION PARKOUR PARK TOKYO",
    nameJa: "ミッション パルクールパーク 東京",
    type: "parkour",
    typeLabel: "パルクール",
    address: "東京都江戸川区松江2-27-15",
    area: "東京 / 江戸川区",
    distance: 9.8,
    lat: 35.6994,
    lng: 139.8734,
    tags: ["国内最大級", "フォームピット", "初心者歓迎"],
    description:
      "国内最大規模のパルクール専用施設。トランポリンやフォームピット、海外規格のオブスタクルを備え、8名のコーチが在籍する。",
    photos: [{ label: "MISSION PARKOUR PARK TOKYO — 写真準備中", color: "ok-lime" }],
    links: {
      web: "https://missionparkourpark.com",
      instagram: "@missiontokyo",
      twitter: "@mission_tokyo_",
    },
    phone: "03-5879-2291",
    price: "¥3,000 / オープンジム",
    equipment: [
      "トランポリン",
      "タンブリングフロア",
      "体操マット",
      "跳び箱",
      "フォームピット",
      "パルクール用オブスタクル",
    ],
    features: ["国内最大級のパルクール専用施設", "コーチ8名在籍", "フォームピット完備", "女性向けFriday枠"],
    lessons: {
      available: true,
      types: ["パルクールレッスン", "アクロバットレッスン", "プライベートレッスン", "ウィメンズフライデー"],
      schedule: "レッスン ¥4,000 / 学割 ¥2,000",
      price: "¥3,000〜",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン"], leadTime: "—" },
    payment: ["現金", "オンライン決済"],
  },
  {
    id: "f02",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "PTvillage PARK",
    nameJa: "ピーティーヴィレッジ パーク",
    type: "mixed",
    typeLabel: "パルクール / アクロバット",
    address: "東京都大田区下丸子3-28-7 中島ビル1F",
    area: "東京 / 大田区",
    distance: 14.6,
    lat: 35.5679,
    lng: 139.684,
    tags: ["キッズクラス充実", "大人クラスあり", "鬼ごっこ運営"],
    description:
      "パルクールメディア『PTvillage』と鬼ごっこ『Onibat』が共同運営する練習施設。年少から大人まで多彩なクラスを開講。",
    photos: [{ label: "PTvillage PARK — 写真準備中", color: "ok-amber" }],
    links: {
      web: "https://park.pt-village.com",
      instagram: "@ptvillage_park",
      twitter: "@pt_village",
      youtube: "@PTvillage",
      tiktok: "@ptvillage_park",
    },
    image: "https://park.pt-village.com/wp-content/uploads/2023/11/PTvillage-PARK_MV.png",
    phone: "03-6715-0707",
    price: "月額 ¥9,800〜 / 入会金 ¥3,000",
    lessons: {
      available: true,
      types: ["ビギナー(年少〜小3)", "ベーシック", "アドバンス", "トレーサー", "大人クラス", "アクロバットクラス"],
      schedule: "月〜土 16:00-20:50",
      price: "月額 ¥9,800〜",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["公式LINE", "会員ポータル(hacomono)"],
      leadTime: "—",
    },
  },
  {
    id: "f03",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "アクロバットジム ホワイト 錦糸町店",
    nameJa: "アクロバットジム ホワイト 錦糸町",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "東京都墨田区亀沢4-16-10 加藤鉄鋼倉庫",
    area: "東京 / 墨田区",
    distance: 4.1,
    lat: 35.6977,
    lng: 139.8069,
    tags: ["バク転", "リノベ倉庫", "貸切OK"],
    description:
      "錦糸町駅近くの鉄鋼倉庫をリノベしたアクロバット施設。15mエアマットを備え、バク転からパルクール・トリッキングまで対応。",
    photos: [{ label: "アクロバットジム ホワイト 錦糸町 — 写真準備中", color: "ok-slate" }],
    links: { web: "https://acrowhite.com", instagram: "@acrowhite" },
    image: "https://acrowhite.com/wpw/wp-content/uploads/2020/03/white_black.jpg",
    phone: "080-4901-0902",
    hours: [
      { day: "月", time: "16:00 - 21:00" },
      { day: "火", time: "16:00 - 21:00" },
      { day: "水", time: "16:00 - 21:00" },
      { day: "木", time: "16:00 - 21:00" },
      { day: "金", time: "16:00 - 21:00" },
      { day: "土", time: "16:00 - 21:00" },
      { day: "日", time: "16:00 - 21:00" },
    ],
    price: "都度・回数券制",
    equipment: ["15mエアマット", "ミニトランポリン", "大型エバーマット", "チアマット"],
    features: ["205㎡・天井8m超", "リノベ倉庫", "貸切・プライベート対応"],
    lessons: {
      available: true,
      types: ["バク転基礎", "幼児・小学生クラス", "パルクール", "トリッキング", "チアタンブリング", "プライベートレッスン"],
      schedule: "クラスにより異なる",
      price: "入会金 ¥8,000 + スポーツ保険 ¥2,000",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン", "電話(当日)"], leadTime: "前日まで" },
    payment: ["クレジットカード", "電子マネー", "交通系IC", "QRコード決済"],
  },
  {
    id: "f04",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    openedAt: "2022-10-03",
    name: "トリッキング&アクロバットスタジオ HERO",
    nameJa: "ヒーロー スタジオ",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "東京都大田区仲六郷2-16-11",
    area: "東京 / 大田区",
    distance: 14.3,
    lat: 35.5655,
    lng: 139.6975,
    tags: ["トリッキング", "アクロバット", "雑色駅"],
    description: "世界チャンピオンが手掛ける、都内のトリッキング&アクロバット専門スタジオ。雑色駅から徒歩3分。",
    photos: [{ label: "HERO STUDIO — 写真準備中", color: "ok-lime" }],
    links: { web: "https://herostudio.studio.site/", instagram: "@herostudio_2022" },
    image:
      "https://storage.googleapis.com/production-os-assets/assets/72d7f909-7018-47b3-a63a-6faddddf4fb7",
  },
  {
    id: "f05",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "TOKYO PARKOUR ACADEMY",
    nameJa: "東京パルクールアカデミー",
    type: "parkour",
    typeLabel: "パルクール",
    address: "東京都豊島区西池袋5-12-3",
    area: "東京 / 豊島区",
    distance: 7.9,
    lat: 35.7289,
    lng: 139.7021,
    tags: ["パルクール", "池袋"],
    description: "西池袋に拠点を置くパルクール専門スクール。",
    photos: [{ label: "TOKYO PARKOUR ACADEMY — 写真準備中", color: "ok-amber" }],
    links: {},
  },
  {
    id: "f06",
    registeredAt: "2026-05-21",
    updatedAt: "2026-06-25",
    name: "G-Rockets STUDIO",
    nameJa: "ジーロケッツ スタジオ",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都葛飾区堀切5-20-5",
    area: "東京 / 葛飾区",
    distance: 9.1,
    lat: 35.7465,
    lng: 139.827,
    tags: ["アクロバット", "バク転", "体験あり"],
    description:
      "葛飾区のアクロバット・バク転教室。舞台やテレビで活躍する現役ダンサー集団 G-Rockets のメンバーが、バク転からアクロバットダンス・リズム新体操・エアリアルまで指導する。",
    photos: [{ label: "G-Rockets STUDIO — 写真準備中", color: "ok-slate" }],
    links: { web: "https://g-rockets-studio.com/" },
    image: "https://g-rockets-studio.com/sys/wp-content/uploads/2020/06/wp-homeimg.jpg",
    phone: "03-3372-5465",
    price: "体験レッスン ¥1,000",
    features: ["現役プロダンサーが指導", "初心者〜経験者対応", "キッズ〜大人クラス", "体験レッスンあり"],
    lessons: {
      available: true,
      types: ["バク転クラス", "アクロバットダンス", "キッズアクロ", "リズム新体操", "エアリアルワークショップ", "プライベートレッスン"],
      schedule: "受付 10:30〜18:00",
      price: "体験 ¥1,000〜",
    },
    booking: { required: true, walkIn: false, methods: ["電話", "FAX", "メール", "オンラインフォーム"], leadTime: "—" },
  },
  {
    id: "f07",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "CROSPO 八王子",
    nameJa: "クロスポ 八王子",
    type: "mixed",
    typeLabel: "屋内スポーツ施設",
    address: "東京都八王子市万町53-1",
    area: "東京 / 八王子市",
    distance: 39.3,
    lat: 35.6529,
    lng: 139.3337,
    tags: ["屋内スポーツ", "トランポリン", "ファミリー向け"],
    description: "トランポリンやボルダリングなどを備えた屋内スポーツアミューズメント施設。パルクール・アクロバットも体験可能。",
    photos: [{ label: "CROSPO 八王子 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://crospo.jp" },
  },
  {
    id: "f08",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "MONKEYS PARKOUR PARK YOKOHAMA",
    nameJa: "モンキーズ パルクールパーク 横浜",
    type: "parkour",
    typeLabel: "パルクール",
    address: "神奈川県横浜市港北区綱島東4-11-21",
    area: "神奈川 / 横浜市",
    distance: 20.0,
    lat: 35.5367,
    lng: 139.6347,
    tags: ["パルクール", "少人数制", "キッズ〜大人"],
    description:
      "横浜・綱島の屋内パルクール専用パーク。2023年7月オープン、40坪・天井高5mで、最大8名の少人数制でパルクール・アクロバット・ダンスを指導する。",
    photos: [{ label: "MONKEYS PARKOUR PARK YOKOHAMA — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.parkour-monkeys.com/" },
    image:
      "https://static.wixstatic.com/media/f8b6d4_5fe2d1bf5f2e4055be2afa8edbfcc11e~mv2.jpg/v1/fit/w_2500,h_1330,al_c/f8b6d4_5fe2d1bf5f2e4055be2afa8edbfcc11e~mv2.jpg",
    phone: "045-716-9916",
    price: "体験 ¥1,000",
    priceDay: "月謝(月4回) 幼児¥6,920〜 / 小学生¥8,350〜 / 大人¥12,500〜 ・ 単発 ¥2,500〜",
    equipment: ["セーフティマット", "平均台", "跳び箱型オブスタクル", "鉄棒", "アクロバットマット", "ダンススタジオ"],
    features: ["2023年7月オープン・神奈川県初の屋内パルクール施設", "40坪・天井高5m", "最大8名の少人数指導", "年齢別・レベル別クラス"],
    lessons: {
      available: true,
      types: ["バランス", "障害物", "鉄棒", "アクロバット", "ダンス(HIPHOP)", "マンツーマンレッスン"],
      schedule: "幼児・小学生・中高大学生・大人の年齢別クラス",
      price: "体験 ¥1,000 / 月謝 ¥6,920〜",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["オンライン予約(RESERVA)", "公式LINE"],
      leadTime: "—",
    },
    payment: ["口座振替"],
  },
  {
    id: "f09",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Yamato Tricking Academy 大和",
    nameJa: "やまとトリッキングアカデミー 大和校",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "神奈川県大和市上草柳1-1-1",
    area: "神奈川 / 大和市",
    distance: 36.7,
    lat: 35.4779,
    lng: 139.447,
    tags: ["トリッキング", "殺陣・アクション", "キッズ〜大人"],
    description:
      "神奈川を中心に多店舗展開するトリッキング専門アカデミーの大和本校。現役パフォーマーがトリッキング・アクロバット・殺陣・アクションを指導する。",
    photos: [{ label: "Yamato Tricking Academy — 写真準備中", color: "ok-slate" }],
    links: { web: "https://www.yamato-tricking.jp/", instagram: "@yamatotrickingstudio" },
    image:
      "https://image.jimcdn.com/app/cms/image/transf/none/path/s575d64a5569cf7cd/image/i3370ee8842e51584/version/1656758621/image.jpg",
    features: ["現役パフォーマーが指導", "メディア出演実績", "キッズ〜大人・初心者対応"],
    lessons: {
      available: true,
      types: ["トリッキングクラス", "アクロバットレッスン", "殺陣・芝居レッスン", "アクションレッスン", "芸能クラス", "個人レッスン"],
      schedule: "予約制（24時間オンライン予約可）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約"], leadTime: "—" },
  },
  {
    id: "f10",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "POWERBOMB",
    nameJa: "パワーボム",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "神奈川県横浜市鶴見区矢向1-6-29",
    area: "神奈川 / 横浜市",
    distance: 18.9,
    lat: 35.5279,
    lng: 139.6764,
    tags: ["アクロバット", "横浜"],
    description: "横浜・鶴見のアクロバット専門ジム。",
    photos: [{ label: "POWERBOMB — 写真準備中", color: "ok-lime" }],
    links: {},
  },
  {
    id: "f11",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Backflip School GRANT 鷺沼",
    nameJa: "バックフリップスクール グラント 鷺沼校",
    type: "mixed",
    typeLabel: "アクロバット / バク転",
    address: "神奈川県川崎市宮前区鷺沼3-1-37",
    area: "神奈川 / 川崎市",
    distance: 20.9,
    lat: 35.5794,
    lng: 139.5729,
    tags: ["バク転", "アクロバット"],
    description: "川崎・鷺沼のバク転・アクロバットスクール。",
    photos: [{ label: "Backflip School GRANT 鷺沼 — 写真準備中", color: "ok-amber" }],
    links: { web: "https://b-s-grant.net/", instagram: "@bakuten___grant" },
  },
  {
    id: "f12",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "POWER ARTS",
    nameJa: "パワーアーツ",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "大阪府大阪市港区波除6-5-16",
    area: "大阪 / 大阪市",
    distance: 407,
    lat: 34.6688,
    lng: 135.4628,
    tags: ["総合", "大阪"],
    description: "大阪・港区のパルクール/トリッキング/アクロバット総合施設。",
    photos: [{ label: "POWER ARTS — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f13",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Gorilla Park",
    nameJa: "ゴリラパーク",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "大阪府松原市天美北5-13-8",
    area: "大阪 / 松原市",
    distance: 403,
    lat: 34.5934,
    lng: 135.5339,
    tags: ["総合", "パーク型"],
    description: "松原市のパルクール/トリッキング/アクロバットパーク。",
    photos: [{ label: "Gorilla Park — 写真準備中", color: "ok-lime" }],
    links: {},
  },
  {
    id: "f14",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Volare Gymnastics Club",
    nameJa: "ヴォラーレ体操クラブ",
    type: "mixed",
    typeLabel: "体操 / アクロバット",
    address: "大阪府岸和田市小松里町2282",
    area: "大阪 / 岸和田市",
    distance: 419,
    lat: 34.4626,
    lng: 135.4042,
    tags: ["体操クラブ", "アクロバット"],
    description: "岸和田市の体操クラブ。パルクール・トリッキング・アクロバットにも対応。",
    photos: [{ label: "Volare Gymnastics Club — 写真準備中", color: "ok-amber" }],
    links: {},
  },
  {
    id: "f15",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "JUMCREET KYOTO",
    nameJa: "ジャムクリート 京都",
    type: "parkour",
    typeLabel: "パルクール",
    address: "京都府京都市山科区西野左義長町26-2",
    area: "京都 / 京都市",
    distance: 367,
    lat: 34.9797,
    lng: 135.8089,
    tags: ["京都初", "全天候型", "完全予約制"],
    description: "京都初の、天候に左右されない屋内パルクール施設。京都モチーフの内装が特徴。",
    photos: [{ label: "JUMCREET KYOTO — 写真準備中", color: "ok-slate" }],
    links: { web: "https://jumcreet.com", instagram: "@jumcreet_kyoto", twitter: "@jumcreet_kyoto" },
    hours: [
      { day: "月", time: "12:00 - 21:00" },
      { day: "火", time: "定休日", closed: true },
      { day: "水", time: "12:00 - 21:00" },
      { day: "木", time: "12:00 - 21:00" },
      { day: "金", time: "12:00 - 21:00" },
      { day: "土", time: "12:00 - 21:00" },
      { day: "日", time: "12:00 - 21:00" },
    ],
    price: "オープンジム ¥2,000〜2,500 / 回",
    equipment: ["固定・可動オブスタクル", "レール", "セーフティマット", "フォームピット", "懸垂バー", "ジャンプボード"],
    features: ["京都初の屋内パルクール施設", "全天候型", "京都モチーフの内装"],
    lessons: {
      available: true,
      types: ["ビギナー", "キッズ", "スピードラン", "アクロバット", "バク転", "パルクール基礎", "上級トレーサー"],
      schedule: "—",
      price: "¥3,000〜5,000 / 回",
    },
    booking: { required: true, walkIn: false, methods: ["公式LINE"], leadTime: "完全予約制" },
  },
  {
    id: "f16",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "パルクールパーク MAX ATTACK",
    nameJa: "パルクールパーク マックスアタック",
    type: "parkour",
    typeLabel: "パルクール",
    address: "愛知県長久手市塚田1504",
    area: "愛知 / 長久手市",
    distance: 252,
    lat: 35.1838,
    lng: 137.0487,
    tags: ["愛知初", "全天候型", "パルクール専用"],
    description: "愛知初の全天候型パルクール施設。跳ぶ・登る・回転する動きを初心者から楽しめる。",
    photos: [{ label: "MAX ATTACK — 写真準備中", color: "ok-lime" }],
    links: { web: "https://www.parkourpark-maxattack.com", instagram: "@maxattack_fujigaoka" },
    image:
      "https://static.wixstatic.com/media/aacff4_f85f13b2b2cd4e1192c7cb8a60affccf~mv2.jpg/v1/fill/w_2500,h_1406,al_c/aacff4_f85f13b2b2cd4e1192c7cb8a60affccf~mv2.jpg",
    equipment: ["パルクール用オブスタクル(跳躍・クライミング・回転)"],
    features: ["愛知初の全天候型パルクール施設"],
    lessons: {
      available: true,
      types: ["パルクール教室"],
      schedule: "曜日制(木曜定休)",
      price: "要問合せ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン"], leadTime: "—" },
  },
  {
    id: "f17",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Studio B-st",
    nameJa: "スタジオ ビースト",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "愛知県名古屋市天白区植田西2-208",
    area: "愛知 / 名古屋市",
    distance: 259,
    lat: 35.1284,
    lng: 136.9889,
    tags: ["総合", "名古屋"],
    description: "名古屋・天白区のパルクール/トリッキング/アクロバットスタジオ。",
    photos: [{ label: "Studio B-st — 写真準備中", color: "ok-amber" }],
    links: {},
  },
  {
    id: "f18",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Ability Parkour ＠CHIKUSHI",
    nameJa: "アビリティ パルクール ＠筑紫",
    type: "parkour",
    typeLabel: "パルクール",
    address: "福岡県筑紫野市筑紫609-2",
    area: "福岡 / 筑紫野市",
    distance: 880,
    lat: 33.4875,
    lng: 130.5259,
    tags: ["パルクール", "福岡"],
    description: "福岡・筑紫野市のパルクール施設。",
    photos: [{ label: "Ability Parkour ＠CHIKUSHI — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f19",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "IS PARKOUR STUDIO",
    nameJa: "アイエス パルクールスタジオ",
    type: "parkour",
    typeLabel: "パルクール",
    address: "福岡県北九州市小倉北区高峰町16-12",
    area: "福岡 / 北九州市",
    distance: 836,
    lat: 33.8837,
    lng: 130.8779,
    tags: ["パルクール", "北九州"],
    description: "北九州・小倉のパルクールスタジオ。",
    photos: [{ label: "IS PARKOUR STUDIO — 写真準備中", color: "ok-lime" }],
    links: {},
  },
  {
    id: "f20",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "MISSION PARKOUR PARK HIROSHIMA",
    nameJa: "ミッション パルクールパーク 広島",
    type: "parkour",
    typeLabel: "パルクール",
    address: "広島県広島市西区大芝3-3-1",
    area: "広島 / 広島市",
    distance: 679,
    lat: 34.4232,
    lng: 132.4616,
    tags: ["パルクール専用", "フォームピット"],
    description: "MISSION PARKOUR PARK の広島店。大人から子どもまで楽しめるパルクール専用パーク。",
    photos: [{ label: "MISSION PARKOUR PARK HIROSHIMA — 写真準備中", color: "ok-amber" }],
    links: { web: "https://missionparkourpark.com/hiroshima/" },
    equipment: ["トランポリン", "タンブリングフロア", "フォームピット", "パルクール用オブスタクル"],
    features: ["MISSION PARKOUR PARK 広島店", "大人から子どもまで"],
    lessons: {
      available: true,
      types: ["パルクールレッスン", "オープンジム"],
      schedule: "—",
      price: "要問合せ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン"], leadTime: "—" },
    payment: ["現金"],
  },
  {
    id: "f21",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Everfit Fukuyama",
    nameJa: "エバーフィット 福山",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "広島県福山市引野町5-32-23",
    area: "広島 / 福山市",
    distance: 593,
    lat: 34.4941,
    lng: 133.4154,
    tags: ["総合", "福山"],
    description: "福山市のパルクール/トリッキング/アクロバットに対応するフィットネス施設。",
    photos: [{ label: "Everfit Fukuyama — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f22",
    registeredAt: "2026-05-21",
    updatedAt: "2026-06-25",
    name: "テラのアクロバット・体操教室",
    nameJa: "テラのアクロバット・体操教室",
    type: "mixed",
    typeLabel: "体操 / アクロバット",
    address: "東京都大田区中央7-4-1",
    area: "東京 / 大田区",
    distance: 14.1,
    lat: 35.5612,
    lng: 139.7158,
    tags: ["バク転", "体操", "大人可"],
    description:
      "大田区のバク転・体操・パルクール教室。登録者10万人超のYouTuber講師『テラ』が、習いたい技に合わせてマンツーマン〜少人数で指導する。",
    photos: [{ label: "テラのアクロバット・体操教室 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://tera757.wpx.jp/" },
    image: "https://tera757.wpx.jp/wp-content/uploads/2022/05/terra-lesson.jpg",
    price: "パーソナル ¥12,000〜/時間",
    priceDay: "少人数 ¥6,000〜/時間 ・ 自主練 ¥3,000〜/時間",
    equipment: ["エバーマット", "短マット", "エアーマット"],
    features: ["YouTube登録者10万人超の講師", "補助ありバク転まで対応", "大人受講可", "マンツーマン中心"],
    lessons: {
      available: true,
      types: ["パーソナルレッスン", "少人数レッスン", "出張レッスン", "バク転教室", "パルクール教室", "スタジオレンタル(自主練)"],
      schedule: "完全予約制（体験レッスンなし）",
      price: "パーソナル ¥12,000〜/時間",
    },
    booking: { required: true, walkIn: false, methods: ["お問い合わせフォーム"], leadTime: "—" },
  },
  {
    id: "f23",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "トリッキング&アクロバットスタジオ HERO 2号店",
    nameJa: "ヒーロー スタジオ 2号店",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "東京都大田区矢口1-5-1",
    area: "東京 / 大田区",
    distance: 14.1,
    lat: 35.5612,
    lng: 139.7158,
    tags: ["トリッキング", "大田区"],
    description: "大田区のトリッキング教室。",
    photos: [{ label: "トリッキング&アクロバットスタジオ HERO 2号店 — 写真準備中", color: "ok-amber" }],
    links: { web: "https://herostudio.studio.site/", instagram: "@herostudio_2022" },
    image: "https://storage.googleapis.com/production-os-assets/assets/72d7f909-7018-47b3-a63a-6faddddf4fb7",
  },
  {
    id: "f24",
    registeredAt: "2026-05-21",
    updatedAt: "2026-06-25",
    name: "アクロバットジム ホワイト 荻窪店",
    nameJa: "アクロバットジム ホワイト 荻窪",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "東京都杉並区清水3-16-7",
    area: "東京 / 杉並区",
    distance: 14.3,
    lat: 35.717,
    lng: 139.6145,
    tags: ["アクロバット", "パルクール", "パワームーブ"],
    description:
      "杉並区・荻窪のアクロバット教室。タンブリングフロアやエアマットを備え、アクロバット・パルクールに加え、荻窪店独自のパワームーブ専門クラスを開講する。",
    photos: [{ label: "アクロバットジム ホワイト 荻窪店 — 写真準備中", color: "ok-slate" }],
    links: { web: "https://acrowhite.com/", instagram: "@acrowhite" },
    image: "https://acrowhite.com/wpw/wp-content/uploads/2020/03/white_black.jpg",
    phone: "070-6516-8768",
    equipment: ["タンブリングフロア", "クッションフロア", "エアマット", "エバーマット", "ミニトランポリン", "大型ミラー"],
    features: ["タンブリングフロア完備", "パワームーブ専門クラス（荻窪店限定）", "初心者対応"],
    lessons: {
      available: true,
      types: ["アクロバットクラス", "パルクールクラス", "パワームーブ専門クラス"],
      schedule: "前日までに要予約（当日予約は +¥500）",
      price: "体験 = 会員受講料金 +¥1,000",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["電話 070-6516-8768", "RESERVA（オンライン）"],
      leadTime: "前日まで（当日予約は +¥500）",
    },
  },
  {
    id: "f25",
    registeredAt: "2026-05-21",
    updatedAt: "2026-06-25",
    name: "W NIHONBASHI",
    nameJa: "ダブル日本橋",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "東京都中央区新川1-2-14",
    area: "東京 / 中央区",
    distance: 1.2,
    lat: 35.6706,
    lng: 139.772,
    tags: ["都内最大級", "アクロバット", "キッズ〜大人"],
    description:
      "日本橋にある都内最大級のアクロバットジム。アクロバット・パルクール・トリッキングを、キッズ・フリー・パーソナルを含む5カテゴリーで初心者から学べる。",
    photos: [{ label: "W NIHONBASHI — 写真準備中", color: "ok-lime" }],
    links: {
      web: "https://w-nihonbashi.com/",
      twitter: "@acrownihonbashi",
      instagram: "@w_nihonbashi_",
      tiktok: "@acrowhite_wnihonbashi",
    },
    image: "https://w-nihonbashi.com/wpw/wp-content/uploads/2024/04/861915301711aa77098d103af3ed361c.png",
    features: ["都内最大級", "駅近", "初心者対応", "キッズ〜大人"],
    lessons: {
      available: true,
      types: ["アクロバット", "パルクール", "キッズ（小学生以下）", "フリー", "パーソナル"],
      schedule: "予約推奨（hacomono / 公式LINE）",
      price: "要問い合わせ",
    },
    booking: {
      required: false,
      walkIn: true,
      methods: ["予約サイト（hacomono）", "公式LINE"],
      leadTime: "—",
    },
  },
  {
    id: "f26",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "スタジオBOS 板橋",
    nameJa: "スタジオ ビーオーエス 板橋",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都板橋区若木1-26-9",
    area: "東京 / 板橋区",
    distance: 9.4,
    lat: 35.7513,
    lng: 139.7088,
    tags: ["総合", "板橋区"],
    description: "板橋区のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "スタジオBOS 板橋 — 写真準備中", color: "ok-amber" }],
    links: { web: "http://www.studio-bos.com/", instagram: "@studio_bos_" },
  },
  {
    id: "f27",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "スタジオBOS 錦糸町",
    nameJa: "スタジオ ビーオーエス 錦糸町",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都墨田区江東橋5-7-22",
    area: "東京 / 墨田区",
    distance: 4.5,
    lat: 35.7104,
    lng: 139.8017,
    tags: ["総合", "墨田区"],
    description: "墨田区のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "スタジオBOS 錦糸町 — 写真準備中", color: "ok-slate" }],
    links: { web: "http://studio-bos-kinshicho.com/", instagram: "@studio_bos_" },
  },
  {
    id: "f28",
    registeredAt: "2026-05-21",
    updatedAt: "2026-06-25",
    name: "PARKOUR TOKYO MAGOME STUDIO",
    nameJa: "パルクール東京 馬込スタジオ",
    type: "parkour",
    typeLabel: "パルクール",
    address: "東京都大田区中馬込2-25-11",
    area: "東京 / 大田区",
    distance: 14.1,
    lat: 35.5612,
    lng: 139.7158,
    tags: ["パルクール", "初心者向け", "フリー練習会"],
    description:
      "大田区・馬込のパルクール専門教室。PARKOUR TOKYO CHAMPIONSHIP 2022 を運営した株式会社STRUGLEが運営し、初心者向けレッスンとフリー練習会を開催する。",
    photos: [{ label: "PARKOUR TOKYO MAGOME STUDIO — 写真準備中", color: "ok-lime" }],
    links: {
      web: "https://www.parkourtokyomagome.com/",
      instagram: "@parkour_magome",
      tiktok: "@parkour_magome",
    },
    price: "1レッスン ¥3,000",
    priceDay: "初回お試し ¥1,000 ・ 回数券8回 ¥20,000 ・ 年会費 ¥5,000（保険込）",
    features: ["初心者向けプログラム", "受賞歴のある講師", "フリー練習会あり"],
    lessons: {
      available: true,
      types: ["初回お試しレッスン", "通常レッスン（1時間）", "フリー練習会"],
      schedule: "予約制（Googleフォーム）",
      price: "1レッスン ¥3,000（初回 ¥1,000）",
    },
    booking: { required: true, walkIn: false, methods: ["Googleフォーム"], leadTime: "—" },
  },
  {
    id: "f29",
    registeredAt: "2026-05-21",
    updatedAt: "2026-06-25",
    openedAt: "2006年",
    name: "つばさ基地",
    nameJa: "つばさ基地",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都板橋区向原2-10-7",
    area: "東京 / 板橋区",
    distance: 9.4,
    lat: 35.7513,
    lng: 139.7088,
    tags: ["体操", "アクション", "バック転"],
    description:
      "板橋区のアクション＆アクロバットスタジオ。2006年創立のつばさプロジェクトが運営し、体操・バク転からアクション・特殊技能まで、資格保有の講師が指導する。",
    photos: [{ label: "つばさ基地 — 写真準備中", color: "ok-amber" }],
    links: { web: "https://tsubasa-kichi.net/" },
    phone: "03-6789-0015",
    features: ["2006年創立", "指導者資格保有の講師", "現役選手・アクション俳優が在籍", "見学無料"],
    lessons: {
      available: true,
      types: ["アクロバット（体操）", "キッズ", "カラダ作り", "特殊技能", "アクション", "バック転専門", "ストレッチ", "ワークショップ"],
      schedule: "要予約（体験予約あり）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["公式サイト予約フォーム"], leadTime: "—" },
  },
  {
    id: "f31",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "スポーツテラス・ガーヤ 上町駅前スタジオ",
    nameJa: "スポーツテラス・ガーヤ 上町",
    type: "mixed",
    typeLabel: "体操 / アクロバット",
    address: "東京都世田谷区世田谷3-4-1",
    area: "東京 / 世田谷区",
    distance: 11,
    lat: 35.6469,
    lng: 139.6525,
    tags: ["体操", "アクロバット", "キッズ"],
    description:
      "世田谷区・上町のジュニア向けスポーツスタジオ。体操・ダンス・チア・アクロバットを子ども向けに指導する。",
    photos: [{ label: "スポーツテラス・ガーヤ 上町駅前スタジオ — 写真準備中", color: "ok-lime" }],
    links: { web: "https://st-gaya.com/setagaya/" },
    image: "https://st-gaya.com/img/logo-color.svg",
    phone: "03-5426-5234",
    features: ["ジュニア(子ども)向け", "体験レッスンあり"],
    lessons: {
      available: true,
      types: ["体操", "ダンス", "チアリーディング", "アクロバット", "IDOL DANCE"],
      schedule: "体験レッスン受付中",
      price: "要問い合わせ",
    },
  },
  {
    id: "f32",
    registeredAt: "2026-05-21",
    updatedAt: "2026-06-25",
    name: "バク転教室東京マッハ",
    nameJa: "バク転教室東京マッハ",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都豊島区北大塚2-2-10",
    area: "東京 / 豊島区",
    distance: 6.8,
    lat: 35.7259,
    lng: 139.7166,
    tags: ["バク転", "パーソナル", "大塚駅1分"],
    description:
      "大塚駅徒歩1分のバク転・アクロバット教室。完全マンツーマンのパーソナルセッションで、バク転・バク宙・ロンダートからの連続技までを指導する。",
    photos: [{ label: "バク転教室東京マッハ — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.machbody.com/" },
    image: "https://image.jimcdn.com/app/cms/image/transf/none/path/s98bd6b643ab21343/image/if4d00e50a1385cd8/version/1778545175/image.jpg",
    price: "完全パーソナル 60分 ¥15,000（税別）",
    hours: [
      { day: "月", time: "6:00 - 23:59" },
      { day: "火", time: "6:00 - 23:59" },
      { day: "水", time: "6:00 - 23:59" },
      { day: "木", time: "6:00 - 23:59" },
      { day: "金", time: "6:00 - 23:59" },
      { day: "土", time: "6:00 - 23:59" },
      { day: "日", time: "6:00 - 23:59" },
    ],
    features: ["大塚駅徒歩1分", "完全マンツーマン貸切", "早朝〜深夜まで対応"],
    lessons: {
      available: true,
      types: ["完全パーソナルセッション（マンツーマン貸切）"],
      schedule: "毎日 6:00〜23:59",
      price: "60分 ¥15,000（税別）",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["オンライン予約（Coubic / RESERVA）"],
      leadTime: "—",
    },
  },
  {
    id: "f33",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "スタジオS",
    nameJa: "スタジオ エス",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都江戸川区松江2-33-7",
    area: "東京 / 江戸川区",
    distance: 9.6,
    lat: 35.7066,
    lng: 139.8687,
    tags: ["総合", "江戸川区"],
    description: "江戸川区のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "スタジオS — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f34",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "WORSAL B/Cスタジオ",
    nameJa: "ウォーサル B/Cスタジオ",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都世田谷区大原2-23-15",
    area: "東京 / 世田谷区",
    distance: 11,
    lat: 35.6469,
    lng: 139.6525,
    tags: ["バク転", "アクション", "アクロバット"],
    description:
      "世田谷区のアクロバット・バク転スタジオ。株式会社ワーサルが運営し、バク転・アクション・タンブリングなどを指導する。",
    photos: [{ label: "WORSAL B/Cスタジオ — 写真準備中", color: "ok-lime" }],
    links: { web: "https://worsal.com/" },
    image: "https://worsal.com/images/main.jpg",
    phone: "03-5371-0255",
    features: ["バク転・アクション専門", "プロによる指導"],
    lessons: {
      available: true,
      types: ["バク転講座", "オンリーワン講座", "アクションクラス", "タンブリング", "チアリーディング", "ピラティス"],
      schedule: "受付 10:00〜18:00（東京本社）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["お問い合わせフォーム"], leadTime: "—" },
  },
  {
    id: "f35",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "WORSAL Aスタジオ",
    nameJa: "ウォーサル Aスタジオ",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都渋谷区笹塚2-25-2",
    area: "東京 / 渋谷区",
    distance: 6.7,
    lat: 35.6634,
    lng: 139.6965,
    tags: ["バク転", "アクション", "アクロバット"],
    description:
      "渋谷区・笹塚のアクロバット・バク転スタジオ。株式会社ワーサルが運営し、バク転・アクション・タンブリングなどを指導する。",
    photos: [{ label: "WORSAL Aスタジオ — 写真準備中", color: "ok-amber" }],
    links: { web: "https://worsal.com/" },
    image: "https://worsal.com/images/main.jpg",
    phone: "03-5371-0255",
    features: ["バク転・アクション専門", "プロによる指導"],
    lessons: {
      available: true,
      types: ["バク転講座", "オンリーワン講座", "アクションクラス", "タンブリング", "チアリーディング", "ピラティス"],
      schedule: "受付 10:00〜18:00（東京本社）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["お問い合わせフォーム"], leadTime: "—" },
  },
  {
    id: "f36",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "studio MAT",
    nameJa: "スタジオ マット",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都世田谷区喜多見1-2-12",
    area: "東京 / 世田谷区",
    distance: 11,
    lat: 35.6469,
    lng: 139.6525,
    tags: ["タンブリング", "アクロバット", "トリッキング"],
    description:
      "世田谷区・喜多見のアクロバットスタジオ。都内初の公式タンブリング板を備え、初心者から経験者までアクロバット・トリッキング・チア・新体操などを指導する。",
    photos: [{ label: "studio MAT — 写真準備中", color: "ok-slate" }],
    links: {
      web: "https://www.studiomat2015.com/",
      instagram: "@studiomat2015",
      tiktok: "@acrobat_studio_mat",
    },
    phone: "070-5080-5886",
    equipment: ["公式タンブリング板", "アクロバットマット"],
    hours: [
      { day: "月", time: "10:00 - 20:00" },
      { day: "火", time: "定休日", closed: true },
      { day: "水", time: "10:00 - 20:00" },
      { day: "木", time: "10:00 - 20:00" },
      { day: "金", time: "10:00 - 20:00" },
      { day: "土", time: "10:00 - 20:00" },
      { day: "日", time: "10:00 - 20:00" },
    ],
    features: ["都内初の公式タンブリング板", "初心者〜経験者対応", "エンタメ特化のプロ講師", "礼儀・人間性指導を重視"],
    lessons: {
      available: true,
      types: ["タンブリング", "アクロバット", "チア", "体操", "新体操", "ダブルダッチ", "トリッキング", "パルクール"],
      schedule: "体験レッスン随時受付（火曜定休）",
      price: "要問い合わせ",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["電話", "LINE", "お問い合わせフォーム", "公式予約システム"],
      leadTime: "—",
    },
  },
  {
    id: "f37",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Tokyo PK Workshop 秋葉原スタジオ",
    nameJa: "東京PKワークショップ 秋葉原",
    type: "parkour",
    typeLabel: "パルクール",
    address: "東京都台東区浅草橋5-3-2",
    area: "東京 / 台東区",
    distance: 3.7,
    lat: 35.7126,
    lng: 139.7801,
    tags: ["パルクール", "初心者向け", "屋内"],
    description:
      "秋葉原・浅草橋の屋内パルクール教室。Tokyo PK Workshopの系列で、初心者・大人向けに基礎から学べる体験クラス・基礎クラスを開催する。",
    photos: [{ label: "Tokyo PK Workshop 秋葉原スタジオ — 写真準備中", color: "ok-lime" }],
    links: { web: "https://parkour.tokyo/", twitter: "@tokyopkworkshop" },
    features: ["屋内施設", "初心者・大人向け", "朝の時間帯クラス"],
    lessons: {
      available: true,
      types: ["体験クラス", "基礎クラス"],
      schedule: "オンライン予約制（朝の時間帯）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約"], leadTime: "—" },
  },
  {
    id: "f38",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Tokyo PK Workshop 新宿スタジオ",
    nameJa: "東京PKワークショップ 新宿",
    type: "parkour",
    typeLabel: "パルクール",
    address: "東京都新宿区西新宿7-13-7",
    area: "東京 / 新宿区",
    distance: 5.9,
    lat: 35.6938,
    lng: 139.7036,
    tags: ["パルクール", "初心者向け", "屋内"],
    description:
      "西新宿の屋内パルクール教室。Tokyo PK Workshopの系列で、初心者・大人向けに基礎から学べる体験クラス・基礎クラスを開催する。",
    photos: [{ label: "Tokyo PK Workshop 新宿スタジオ — 写真準備中", color: "ok-amber" }],
    links: { web: "https://parkour.tokyo/", twitter: "@tokyopkworkshop" },
    features: ["屋内施設", "初心者・大人向け", "朝の時間帯クラス"],
    lessons: {
      available: true,
      types: ["体験クラス", "基礎クラス"],
      schedule: "オンライン予約制（朝の時間帯）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約"], leadTime: "—" },
  },
  {
    id: "f39",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "バク転パーソナル教室 東京 亀戸店",
    nameJa: "バク転パーソナル教室 亀戸",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都江東区亀戸3-47-16",
    area: "東京 / 江東区",
    distance: 4.6,
    lat: 35.6728,
    lng: 139.817,
    tags: ["バク転", "マンツーマン", "大人可"],
    description:
      "江東区・亀戸のバク転パーソナル教室。日本一のバク転講師が監修するマンツーマン指導で、バク転・側転・ロンダートなどを習得できる。",
    photos: [{ label: "バク転パーソナル教室 東京 亀戸店 — 写真準備中", color: "ok-slate" }],
    links: {
      web: "https://bakuten-personal.com/school/kameido/",
      twitter: "@BakutenTokyo",
      instagram: "@bakutenpersonal.tokyo",
      youtube: "@bakuten.personal_kyousitstu",
    },
    image: "https://bakuten-personal.com/wp-content/uploads/2024/05/opg.jpg",
    phone: "03-6666-9533",
    price: "初回体験 50分 ¥6,600（学割 ¥5,280）",
    priceDay: "単発 50分 ¥8,800 / 80分 ¥13,200 ・ 入会金 ¥11,000 ・ 回数券割引あり",
    equipment: ["エアマット", "動画撮影設備"],
    hours: [
      { day: "月", time: "9:00 - 22:00" },
      { day: "火", time: "9:00 - 22:00" },
      { day: "水", time: "9:00 - 22:00" },
      { day: "木", time: "9:00 - 22:00" },
      { day: "金", time: "9:00 - 22:00" },
      { day: "土", time: "9:00 - 22:00" },
      { day: "日", time: "9:00 - 22:00" },
    ],
    features: ["4歳〜70代対応", "完全マンツーマン・個別カリキュラム", "元日本一監修の研修済み講師", "動画フィードバック"],
    lessons: {
      available: true,
      types: ["マンツーマンレッスン", "2人グループ", "3人グループ"],
      schedule: "完全予約制（受付 9:00〜21:00・定休日なし）",
      price: "初回体験 50分 ¥6,600〜",
    },
    booking: { required: true, walkIn: false, methods: ["公式LINE", "電話"], leadTime: "—" },
    payment: ["クレジットカード", "交通系IC", "PayPay", "LINE Pay"],
  },
  {
    id: "f40",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "バク転パーソナル教室 東京 墨田店",
    nameJa: "バク転パーソナル教室 墨田",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都墨田区立川2-10-10",
    area: "東京 / 墨田区",
    distance: 4.5,
    lat: 35.7104,
    lng: 139.8017,
    tags: ["バク転", "マンツーマン", "大人可"],
    description:
      "墨田区・菊川のバク転パーソナル教室。日本一のバク転講師が監修するマンツーマン指導で、バク転・側転・ロンダートなどを習得できる。菊川駅徒歩8分。",
    photos: [{ label: "バク転パーソナル教室 東京 墨田店 — 写真準備中", color: "ok-lime" }],
    links: {
      web: "https://bakuten-personal.com/school/sumida/",
      twitter: "@BakutenTokyo",
      instagram: "@bakutenpersonal.tokyo",
      youtube: "@bakuten.personal_kyousitstu",
    },
    image: "https://bakuten-personal.com/wp-content/uploads/2024/05/opg.jpg",
    phone: "03-6666-9533",
    price: "初回体験 50分 ¥6,600（学割 ¥5,280）",
    priceDay: "単発 50分 ¥8,800 / 80分 ¥13,200 ・ 入会金 ¥11,000 ・ 回数券割引あり",
    equipment: ["エアマット", "動画撮影設備"],
    features: ["4歳〜70代対応", "完全マンツーマン・個別カリキュラム", "元日本一監修の研修済み講師", "動画フィードバック"],
    lessons: {
      available: true,
      types: ["マンツーマンレッスン", "2人グループ", "3人グループ"],
      schedule: "完全予約制（受付 9:00〜21:00）",
      price: "初回体験 50分 ¥6,600〜",
    },
    booking: { required: true, walkIn: false, methods: ["公式LINE", "電話"], leadTime: "—" },
    payment: ["クレジットカード", "交通系IC", "PayPay", "LINE Pay"],
  },
  {
    id: "f41",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "パルクールスクール四ツ谷",
    nameJa: "パルクールスクール四ツ谷",
    type: "parkour",
    typeLabel: "パルクール",
    address: "東京都千代田区麹町6-6",
    area: "東京 / 千代田区",
    distance: 3.1,
    lat: 35.6822,
    lng: 139.7327,
    tags: ["パルクール", "キッズ専門", "四ツ谷駅2分"],
    description:
      "四ツ谷駅徒歩2分のパルクールスクール。未就学児〜小学生を対象に、パルクールの基礎を楽しく身につけるキッズ向け教室。",
    photos: [{ label: "パルクールスクール四ツ谷 — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.parkour-school.jp/place/yotsuya" },
    features: ["未就学児〜小学生対象", "四ツ谷駅徒歩2分", "キッズ専門"],
    lessons: {
      available: true,
      types: ["パルクール基礎（キッズ）"],
      schedule: "予約制",
      price: "要問い合わせ",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["オンライン予約（RESERVA）"],
      leadTime: "—",
    },
  },
  {
    id: "f42",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "PLAY STREET",
    nameJa: "プレイストリート",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "東京都豊島区西池袋5-11-6",
    area: "東京 / 豊島区",
    distance: 6.8,
    lat: 35.7259,
    lng: 139.7166,
    tags: ["総合", "豊島区"],
    description: "豊島区のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "PLAY STREET — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f43",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "MONKEYS PARKOUR PARK たまプラーザ店",
    nameJa: "モンキーズ パルクールパーク たまプラーザ",
    type: "parkour",
    typeLabel: "パルクール",
    address: "神奈川県横浜市青葉区美しが丘2-21-2",
    area: "神奈川 / 横浜市",
    distance: 26.5,
    lat: 35.4715,
    lng: 139.6275,
    tags: ["パルクール", "少人数制", "キッズ〜大人"],
    description:
      "横浜・たまプラーザのパルクール施設。MONKEYS PARKOUR PARKの系列店で、少人数制でパルクール・アクロバット・ダンスを指導する。",
    photos: [{ label: "MONKEYS PARKOUR PARK たまプラーザ店 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://www.parkour-monkeys.com/", instagram: "@monkeys_yokohama2" },
    price: "体験 ¥1,000",
    equipment: ["セーフティマット", "パルクール用オブスタクル", "鉄棒", "アクロバットマット"],
    features: ["最大8名の少人数指導", "年齢別・レベル別クラス"],
    lessons: {
      available: true,
      types: ["バランス", "障害物", "鉄棒", "アクロバット", "ダンス", "マンツーマンレッスン"],
      schedule: "年齢別クラス（幼児〜大人）",
      price: "体験 ¥1,000",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約", "公式LINE"], leadTime: "—" },
    image: "https://static.wixstatic.com/media/f8b6d4_5fe2d1bf5f2e4055be2afa8edbfcc11e%7Emv2.jpg/v1/fit/w_2500,h_1330,al_c/f8b6d4_5fe2d1bf5f2e4055be2afa8edbfcc11e%7Emv2.jpg",
  },
  {
    id: "f44",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "MONKEYS PARKOUR PARK ラ チッタデッラ店",
    nameJa: "モンキーズ パルクールパーク ラ チッタデッラ",
    type: "parkour",
    typeLabel: "パルクール",
    address: "神奈川県川崎市川崎区小川町4-1",
    area: "神奈川 / 川崎市",
    distance: 18.7,
    lat: 35.5239,
    lng: 139.6933,
    tags: ["パルクール", "少人数制", "キッズ〜大人"],
    description:
      "川崎・ラ チッタデッラのパルクール施設。MONKEYS PARKOUR PARKの系列店で、少人数制でパルクール・アクロバット・ダンスを指導する。",
    photos: [{ label: "MONKEYS PARKOUR PARK ラ チッタデッラ店 — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.parkour-monkeys.com/", instagram: "@monkeys_kawasaki_" },
    price: "体験 ¥1,000",
    equipment: ["セーフティマット", "パルクール用オブスタクル", "鉄棒", "アクロバットマット"],
    features: ["最大8名の少人数指導", "年齢別・レベル別クラス"],
    lessons: {
      available: true,
      types: ["バランス", "障害物", "鉄棒", "アクロバット", "ダンス", "マンツーマンレッスン"],
      schedule: "年齢別クラス（幼児〜大人）",
      price: "体験 ¥1,000",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約", "公式LINE"], leadTime: "—" },
    image: "https://static.wixstatic.com/media/f8b6d4_5fe2d1bf5f2e4055be2afa8edbfcc11e%7Emv2.jpg/v1/fit/w_2500,h_1330,al_c/f8b6d4_5fe2d1bf5f2e4055be2afa8edbfcc11e%7Emv2.jpg",
  },
  {
    id: "f45",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "大和トリッキング教室 鶴間スタジオ",
    nameJa: "やまとトリッキング 鶴間",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "神奈川県大和市鶴間2-13-30",
    area: "神奈川 / 大和市",
    distance: 37.4,
    lat: 35.443,
    lng: 139.4749,
    tags: ["トリッキング", "殺陣・アクション", "大和市"],
    description:
      "大和・鶴間のトリッキング教室。大和トリッキングの系列スタジオで、現役パフォーマーがトリッキング・アクロバット・殺陣・アクションを指導する。",
    photos: [{ label: "大和トリッキング教室 鶴間スタジオ — 写真準備中", color: "ok-slate" }],
    links: { web: "https://www.yamato-tricking.jp/", instagram: "@yamatotrickingstudio" },
    features: ["現役パフォーマーが指導", "少人数制（最大4名）", "小学生〜大人・初心者対応"],
    lessons: {
      available: true,
      types: ["トリッキングクラス", "アクロバットレッスン", "殺陣・芝居レッスン", "アクションレッスン", "芸能クラス", "個人レッスン"],
      schedule: "予約制（24時間オンライン予約可）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約"], leadTime: "—" },
    image: "https://image.jimcdn.com/app/cms/image/transf/none/path/s575d64a5569cf7cd/image/i3370ee8842e51584/version/1656758621/image.jpg",
  },
  {
    id: "f46",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "大和トリッキング教室 藤沢スタジオ",
    nameJa: "やまとトリッキング 藤沢",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "神奈川県藤沢市本町2-8-31",
    area: "神奈川 / 藤沢市",
    distance: 45.9,
    lat: 35.3442,
    lng: 139.4733,
    tags: ["トリッキング", "バク転", "藤沢市"],
    description:
      "藤沢・本町のアクロバット／バク転・トリッキング教室。大和トリッキングの系列で、小学生〜大人が最大4名の少人数制で学べる。藤沢駅近く。",
    photos: [{ label: "大和トリッキング教室 藤沢スタジオ — 写真準備中", color: "ok-lime" }],
    links: { web: "https://www.y-fujisawa-acrobat.com/", instagram: "@yamato.trickingstudio" },
    features: ["少人数制（最大4名）", "小学生〜大人対応", "現役パフォーマーが指導"],
    lessons: {
      available: true,
      types: ["アクロバット／バク転レッスン", "トリッキングクラス", "個人レッスン", "殺陣・芝居レッスン", "アクションレッスン", "芸能クラス"],
      schedule: "予約制（24時間オンライン予約可）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約", "LINE"], leadTime: "—" },
    image: "https://image.jimcdn.com/app/cms/image/transf/none/path/s575d64a5569cf7cd/image/i3370ee8842e51584/version/1656758621/image.jpg",
  },
  {
    id: "f47",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "大和トリッキング教室 相模原スタジオ",
    nameJa: "やまとトリッキング 相模原",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "神奈川県相模原市中央区上溝3-20-22",
    area: "神奈川 / 相模原市",
    distance: 41.1,
    lat: 35.5871,
    lng: 139.327,
    tags: ["トリッキング", "バク転", "相模原市"],
    description:
      "相模原・上溝のアクロバット／バク転・トリッキング教室。大和トリッキングの系列で、小学生〜大人が最大4名の少人数制で学べる。上溝駅徒歩11分。",
    photos: [{ label: "大和トリッキング教室 相模原スタジオ — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.y-sagamihara-acrobat.com/", instagram: "@yamato.trickingstudio" },
    price: "1レッスン60分 ¥2,500（会員 ¥2,000）",
    features: ["少人数制（最大4名）", "小学生〜大人対応", "初心者基礎クラスあり"],
    lessons: {
      available: true,
      types: ["初心者・基礎クラス", "フリークラス", "個人レッスン"],
      schedule: "予約制（24時間オンライン予約可）",
      price: "1レッスン60分 ¥2,500（会員 ¥2,000）",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約", "LINE"], leadTime: "—" },
    image: "https://image.jimcdn.com/app/cms/image/transf/none/path/s575d64a5569cf7cd/image/i3370ee8842e51584/version/1656758621/image.jpg",
  },
  {
    id: "f48",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "大和トリッキング教室 本厚木スタジオ",
    nameJa: "やまとトリッキング 本厚木",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "神奈川県厚木市恩名1-20-27",
    area: "神奈川 / 厚木市",
    distance: 44,
    lat: 35.4868,
    lng: 139.3429,
    tags: ["トリッキング", "殺陣・アクション", "厚木市"],
    description:
      "厚木市のトリッキング教室。大和トリッキングの系列スタジオで、現役パフォーマーがトリッキング・アクロバット・殺陣・アクションを指導する。",
    photos: [{ label: "大和トリッキング教室 本厚木スタジオ — 写真準備中", color: "ok-slate" }],
    links: { web: "https://www.yamato-tricking.jp/", instagram: "@yamatotrickingstudio" },
    features: ["現役パフォーマーが指導", "キッズ〜大人・初心者対応"],
    lessons: {
      available: true,
      types: ["トリッキングクラス", "アクロバットレッスン", "殺陣・芝居レッスン", "アクションレッスン", "芸能クラス", "個人レッスン"],
      schedule: "予約制（24時間オンライン予約可）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約"], leadTime: "—" },
    image: "https://image.jimcdn.com/app/cms/image/transf/none/path/s575d64a5569cf7cd/image/i3370ee8842e51584/version/1656758621/image.jpg",
  },
  {
    id: "f49",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "大和トリッキング教室 東戸塚スタジオ",
    nameJa: "やまとトリッキング 東戸塚",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "神奈川県横浜市戸塚区品濃町881-9",
    area: "神奈川 / 横浜市",
    distance: 26.5,
    lat: 35.4715,
    lng: 139.6275,
    tags: ["トリッキング", "殺陣・アクション", "横浜市"],
    description:
      "横浜・東戸塚のトリッキング教室。大和トリッキングの系列スタジオで、現役パフォーマーがトリッキング・アクロバット・殺陣・アクションを指導する。",
    photos: [{ label: "大和トリッキング教室 東戸塚スタジオ — 写真準備中", color: "ok-lime" }],
    links: { web: "https://www.yamato-tricking.jp/", instagram: "@yamatotrickingstudio" },
    features: ["現役パフォーマーが指導", "キッズ〜大人・初心者対応"],
    lessons: {
      available: true,
      types: ["トリッキングクラス", "アクロバットレッスン", "殺陣・芝居レッスン", "アクションレッスン", "芸能クラス", "個人レッスン"],
      schedule: "予約制（24時間オンライン予約可）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約"], leadTime: "—" },
    image: "https://image.jimcdn.com/app/cms/image/transf/none/path/s575d64a5569cf7cd/image/i3370ee8842e51584/version/1656758621/image.jpg",
  },
  {
    id: "f50",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "大和トリッキング教室 小机スタジオ",
    nameJa: "やまとトリッキング 小机",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "神奈川県横浜市港北区小机町2565-2",
    area: "神奈川 / 横浜市",
    distance: 26.5,
    lat: 35.4715,
    lng: 139.6275,
    tags: ["トリッキング", "横浜市"],
    description:
      "横浜・小机のトリッキング教室。大和トリッキングの系列スタジオで、現役パフォーマーがトリッキング・アクロバット・殺陣・アクションを指導する。",
    photos: [{ label: "大和トリッキング教室 小机スタジオ — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.yamato-tricking.jp/", instagram: "@yamatotrickingstudio" },
    image: "https://image.jimcdn.com/app/cms/image/transf/none/path/s575d64a5569cf7cd/image/i3370ee8842e51584/version/1656758621/image.jpg",
    features: ["現役パフォーマーが指導", "少人数制（最大4名）", "小学生〜大人・初心者対応"],
    lessons: {
      available: true,
      types: ["トリッキングクラス", "アクロバットレッスン", "殺陣・芝居レッスン", "アクションレッスン", "芸能クラス", "個人レッスン"],
      schedule: "予約制（24時間オンライン予約可）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約"], leadTime: "—" },
  },
  {
    id: "f51",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "大和トリッキング教室 大口スタジオ",
    nameJa: "やまとトリッキング 大口",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "神奈川県横浜市神奈川区大口通127-1",
    area: "神奈川 / 横浜市",
    distance: 26.5,
    lat: 35.4715,
    lng: 139.6275,
    tags: ["トリッキング", "横浜市"],
    description:
      "横浜・大口のトリッキング教室。大和トリッキングの系列スタジオで、現役パフォーマーがトリッキング・アクロバット・殺陣・アクションを指導する。",
    photos: [{ label: "大和トリッキング教室 大口スタジオ — 写真準備中", color: "ok-slate" }],
    links: { web: "https://www.yamato-tricking.jp/", instagram: "@yamatotrickingstudio" },
    image: "https://image.jimcdn.com/app/cms/image/transf/none/path/s575d64a5569cf7cd/image/i3370ee8842e51584/version/1656758621/image.jpg",
    features: ["現役パフォーマーが指導", "少人数制（最大4名）", "小学生〜大人・初心者対応"],
    lessons: {
      available: true,
      types: ["トリッキングクラス", "アクロバットレッスン", "殺陣・芝居レッスン", "アクションレッスン", "芸能クラス", "個人レッスン"],
      schedule: "予約制（24時間オンライン予約可）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約"], leadTime: "—" },
  },
  {
    id: "f52",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "大和トリッキング教室 南林間スタジオ",
    nameJa: "やまとトリッキング 南林間",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "神奈川県大和市南林間2-11-4",
    area: "神奈川 / 大和市",
    distance: 37.4,
    lat: 35.443,
    lng: 139.4749,
    tags: ["トリッキング", "大和市"],
    description:
      "大和・南林間のトリッキング教室。大和トリッキングの系列スタジオで、現役パフォーマーがトリッキング・アクロバット・殺陣・アクションを指導する。",
    photos: [{ label: "大和トリッキング教室 南林間スタジオ — 写真準備中", color: "ok-lime" }],
    links: { web: "https://www.yamato-tricking.jp/", instagram: "@yamatotrickingstudio" },
    image: "https://image.jimcdn.com/app/cms/image/transf/none/path/s575d64a5569cf7cd/image/i3370ee8842e51584/version/1656758621/image.jpg",
    features: ["現役パフォーマーが指導", "少人数制（最大4名）", "小学生〜大人・初心者対応"],
    lessons: {
      available: true,
      types: ["トリッキングクラス", "アクロバットレッスン", "殺陣・芝居レッスン", "アクションレッスン", "芸能クラス", "個人レッスン"],
      schedule: "予約制（24時間オンライン予約可）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約"], leadTime: "—" },
  },
  {
    id: "f53",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "大和トリッキング教室 三ツ沢スタジオ",
    nameJa: "やまとトリッキング 三ツ沢",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "神奈川県横浜市神奈川区松本町5-38-1",
    area: "神奈川 / 横浜市",
    distance: 26.5,
    lat: 35.4715,
    lng: 139.6275,
    tags: ["トリッキング", "横浜市"],
    description:
      "横浜・三ツ沢のトリッキング教室。大和トリッキングの系列スタジオで、現役パフォーマーがトリッキング・アクロバット・殺陣・アクションを指導する。",
    photos: [{ label: "大和トリッキング教室 三ツ沢スタジオ — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.yamato-tricking.jp/", instagram: "@yamatotrickingstudio" },
    image: "https://image.jimcdn.com/app/cms/image/transf/none/path/s575d64a5569cf7cd/image/i3370ee8842e51584/version/1656758621/image.jpg",
    features: ["現役パフォーマーが指導", "少人数制（最大4名）", "小学生〜大人・初心者対応"],
    lessons: {
      available: true,
      types: ["トリッキングクラス", "アクロバットレッスン", "殺陣・芝居レッスン", "アクションレッスン", "芸能クラス", "個人レッスン"],
      schedule: "予約制（24時間オンライン予約可）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約"], leadTime: "—" },
  },
  {
    id: "f54",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "大和トリッキング教室 テラスモール湘南",
    nameJa: "やまとトリッキング テラスモール湘南",
    type: "tricking",
    typeLabel: "トリッキング",
    address: "神奈川県藤沢市辻堂神台1-3-1",
    area: "神奈川 / 藤沢市",
    distance: 45.9,
    lat: 35.3442,
    lng: 139.4733,
    tags: ["トリッキング", "藤沢市"],
    description:
      "藤沢・テラスモール湘南のトリッキング教室。大和トリッキングの系列スタジオで、現役パフォーマーがトリッキング・アクロバット・殺陣・アクションを指導する。",
    photos: [{ label: "大和トリッキング教室 テラスモール湘南 — 写真準備中", color: "ok-slate" }],
    links: { web: "https://www.yamato-tricking.jp/", instagram: "@yamatotrickingstudio" },
    image: "https://image.jimcdn.com/app/cms/image/transf/none/path/s575d64a5569cf7cd/image/i3370ee8842e51584/version/1656758621/image.jpg",
    features: ["現役パフォーマーが指導", "少人数制（最大4名）", "小学生〜大人・初心者対応"],
    lessons: {
      available: true,
      types: ["トリッキングクラス", "アクロバットレッスン", "殺陣・芝居レッスン", "アクションレッスン", "芸能クラス", "個人レッスン"],
      schedule: "予約制（24時間オンライン予約可）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約"], leadTime: "—" },
  },
  {
    id: "f55",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "パルクールパーク横浜いずみ",
    nameJa: "パルクールパーク横浜いずみ",
    type: "parkour",
    typeLabel: "パルクール",
    address: "神奈川県横浜市泉区和泉が丘1-16-3",
    area: "神奈川 / 横浜市",
    distance: 26.5,
    lat: 35.4715,
    lng: 139.6275,
    tags: ["パルクール", "横浜市"],
    description: "横浜市のパルクール施設。",
    photos: [{ label: "パルクールパーク横浜いずみ — 写真準備中", color: "ok-lime" }],
    links: { web: "https://peraichi.com/landing_pages/view/kanagawaparkourcommunity/" },
  },
  {
    id: "f56",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "バク転スクールGRANT 梶が谷本校",
    nameJa: "バク転スクールグラント 梶が谷",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "神奈川県川崎市高津区末長1-23-11",
    area: "神奈川 / 川崎市",
    distance: 18.7,
    lat: 35.5239,
    lng: 139.6933,
    tags: ["総合", "川崎市"],
    description: "川崎市のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "バク転スクールGRANT 梶が谷本校 — 写真準備中", color: "ok-amber" }],
    links: { web: "https://b-s-grant.net/", instagram: "@bakuten___grant" },
  },
  {
    id: "f57",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "MiN! アクロバット教室",
    nameJa: "ミン アクロバット教室",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "神奈川県相模原市中央区矢部2-15-10",
    area: "神奈川 / 相模原市",
    distance: 41.1,
    lat: 35.5871,
    lng: 139.327,
    tags: ["総合", "相模原市"],
    description: "相模原市のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "MiN! アクロバット教室 — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f58",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "ニンジャパーク 武蔵浦和店",
    nameJa: "ニンジャパーク 武蔵浦和",
    type: "parkour",
    typeLabel: "パルクール",
    address: "埼玉県さいたま市南区白幡5-11-20",
    area: "埼玉 / さいたま市",
    distance: 20.9,
    lat: 35.8439,
    lng: 139.6524,
    tags: ["トランポリン", "ボルダリング", "アスレチック"],
    description:
      "さいたま市・武蔵浦和の体験型スポーツ施設ニンジャパーク。トランポリンやボルダリング、パルクールエリアを備え、パルクール・アクロバット・トランポリンのレッスンを提供する。",
    photos: [{ label: "ニンジャパーク 武蔵浦和店 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://ninjapark.net/" },
    image: "https://ninjapark.net/wp-content/uploads/2019/11/topimg-1.jpg",
    equipment: ["トランポリン", "ボルダリング", "モンスターボックス(跳び箱)", "ジャイアントウォール", "パルクールエリア", "キッズエリア"],
    features: ["全国13店舗以上のアミューズメントスポーツ", "月額定額で本格レッスン受け放題", "放課後キッズ預かり対応"],
    lessons: {
      available: true,
      types: ["パルクール", "アクロバット", "トランポリン", "ブレイクダンス", "女性限定エクササイズ"],
      schedule: "月額会員・単発会員・キッズスクール",
      price: "要問い合わせ",
    },
    booking: {
      required: false,
      walkIn: true,
      methods: ["チケット購入", "キッズ体験会(予約不要)"],
      leadTime: "—",
    },
  },
  {
    id: "f59",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "acroba",
    nameJa: "アクロバ",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "埼玉県さいたま市大宮区三橋1-1482",
    area: "埼玉 / さいたま市",
    distance: 29,
    lat: 35.9067,
    lng: 139.6056,
    tags: ["体操", "アクロバット", "さいたま市"],
    description:
      "さいたま市・大宮区三橋の体操・アクロバットスタジオ。80坪のスペースでプロパフォーマーが体操・アクロバットを指導し、オープンジムやスタジオレンタルも行う。",
    photos: [{ label: "acroba — 写真準備中", color: "ok-amber" }],
    links: { web: "https://sun-bloom.co.jp/" },
    image: "https://sun-bloom.co.jp/wp-content/uploads/2019/07/-e1563017998765.jpg",
    phone: "048-783-3020",
    features: ["80坪のスタジオ", "プロパフォーマーが指導", "オープンジム・スタジオレンタルあり", "TV出演実績"],
    lessons: {
      available: true,
      types: ["体操", "アクロバット", "短期教室", "ワークショップ"],
      schedule: "電話受付 平日14:00〜21:00 / 土日祝 9:00〜18:00",
      price: "要問い合わせ",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["体験予約フォーム", "Buscatch", "電話"],
      leadTime: "—",
    },
  },
  {
    id: "f60",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "入間市パルクール教室",
    nameJa: "入間市パルクール教室",
    type: "parkour",
    typeLabel: "パルクール",
    address: "埼玉県入間市向陽台2-1-21",
    area: "埼玉 / 入間市",
    distance: 38.1,
    lat: 35.8358,
    lng: 139.3909,
    tags: ["パルクール", "入間市"],
    description: "入間市のパルクール施設。",
    photos: [{ label: "入間市パルクール教室 — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f61",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "パルクールスクール大宮",
    nameJa: "パルクールスクール大宮",
    type: "parkour",
    typeLabel: "パルクール",
    address: "埼玉県さいたま市大宮区天沼町2-759",
    area: "埼玉 / さいたま市",
    distance: 27.9,
    lat: 35.9113,
    lng: 139.6451,
    tags: ["パルクール", "キッズ専門", "さいたま新都心"],
    description:
      "さいたま新都心のパルクール専門スクール。約40坪のパルクールエリアで、6〜12歳が日本選手権上位入賞コーチの指導でバランス・跳躍・登攀などを学ぶ。",
    photos: [{ label: "パルクールスクール大宮 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://www.parkour-school.jp/place/omiya", instagram: "@parkourschool_omiya" },
    features: ["6〜12歳対象", "約40坪のパルクールエリア", "日本選手権上位入賞のコーチ"],
    lessons: {
      available: true,
      types: ["パルクール基礎（キッズ）"],
      schedule: "予約制（hacomono）",
      price: "要問い合わせ",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["オンライン予約（hacomono）"],
      leadTime: "—",
    },
  },
  {
    id: "f62",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "TIER ONE PARKOUR GYM",
    nameJa: "ティアワン パルクールジム",
    type: "parkour",
    typeLabel: "パルクール",
    address: "埼玉県さいたま市桜区桜田3-7-2",
    area: "埼玉 / さいたま市",
    distance: 23,
    lat: 35.8511,
    lng: 139.622,
    tags: ["パルクール", "関東最大級", "さいたま市"],
    description:
      "さいたま市桜区の関東最大級のパルクールジム。スピードコンテスト優勝経験を持つ代表コーチが、大人から子どもまでコミュニティ重視で指導する。",
    photos: [{ label: "TIER ONE PARKOUR GYM — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.tierone-parkourgym.com/" },
    phone: "070-9224-7297",
    features: ["関東最大級の施設", "プレーヤーが設計に関与", "代表コーチは指導実績200名以上・大会優勝経験", "コミュニティ重視"],
    lessons: {
      available: true,
      types: ["パルクール（初心者〜上級）"],
      schedule: "予約制（hacomono）",
      price: "要問い合わせ",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["オンライン予約（hacomono）"],
      leadTime: "—",
    },
  },
  {
    id: "f63",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "ニンジャパーク 五香店",
    nameJa: "ニンジャパーク 五香",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "千葉県松戸市五香8-44-6",
    area: "千葉 / 松戸市",
    distance: 17.2,
    lat: 35.7873,
    lng: 139.9049,
    tags: ["トランポリン", "ボルダリング", "アスレチック"],
    description:
      "松戸市・五香の体験型スポーツ施設ニンジャパーク。トランポリンやボルダリング、パルクールエリアを備え、パルクール・アクロバット・トランポリンのレッスンを提供する。",
    photos: [{ label: "ニンジャパーク 五香店 — 写真準備中", color: "ok-slate" }],
    links: { web: "https://ninjapark.net/matsudo/" },
    equipment: ["トランポリン", "ボルダリング", "モンスターボックス(跳び箱)", "ジャイアントウォール", "パルクールエリア", "キッズエリア"],
    features: ["全国13店舗以上のアミューズメントスポーツ", "月額定額で本格レッスン受け放題", "放課後キッズ預かり対応"],
    lessons: {
      available: true,
      types: ["パルクール", "アクロバット", "トランポリン", "ブレイクダンス", "女性限定エクササイズ"],
      schedule: "月額会員・単発会員・キッズスクール",
      price: "要問い合わせ",
    },
    booking: {
      required: false,
      walkIn: true,
      methods: ["チケット購入", "キッズ体験会(予約不要)"],
      leadTime: "—",
    },
  },
  {
    id: "f64",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "ニンジャパーク 南行徳店",
    nameJa: "ニンジャパーク 南行徳",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "千葉県市川市南行徳2-20-25",
    area: "千葉 / 市川市",
    distance: 13.7,
    lat: 35.6712,
    lng: 139.9183,
    tags: ["トランポリン", "ボルダリング", "アスレチック"],
    description:
      "市川市・南行徳の体験型スポーツ施設ニンジャパーク。トランポリンやボルダリング、パルクールエリアを備え、パルクール・アクロバット・トランポリンのレッスンを提供する。",
    photos: [{ label: "ニンジャパーク 南行徳店 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://ninjapark.net/minami-gyotoku/" },
    equipment: ["トランポリン", "ボルダリング", "モンスターボックス(跳び箱)", "ジャイアントウォール", "パルクールエリア", "キッズエリア"],
    features: ["全国13店舗以上のアミューズメントスポーツ", "月額定額で本格レッスン受け放題", "放課後キッズ預かり対応"],
    lessons: {
      available: true,
      types: ["パルクール", "アクロバット", "トランポリン", "ブレイクダンス", "女性限定エクササイズ"],
      schedule: "月額会員・単発会員・キッズスクール",
      price: "要問い合わせ",
    },
    booking: {
      required: false,
      walkIn: true,
      methods: ["チケット購入", "キッズ体験会(予約不要)"],
      leadTime: "—",
    },
  },
  {
    id: "f65",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Double x Double",
    nameJa: "ダブル バイ ダブル",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "千葉県千葉市中央区浜野町397-13",
    area: "千葉 / 千葉市",
    distance: 32.3,
    lat: 35.6121,
    lng: 140.1142,
    tags: ["バク転", "トランポリン", "予約制"],
    description:
      "千葉市・中央区のトランポリン・アクロバット施設。バク転・バク宙・体操・チア・トリッキングを、初心者と中上級に分けた完全予約制で練習できる。",
    photos: [{ label: "Double x Double — 写真準備中", color: "ok-amber" }],
    links: { web: "https://doublexdouble.jimdofree.com/", instagram: "@dubxdub_official" },
    hours: [
      { day: "月", time: "9:00 - 21:00" },
      { day: "火", time: "9:00 - 21:00" },
      { day: "水", time: "9:00 - 21:00" },
      { day: "木", time: "9:00 - 21:00" },
      { day: "金", time: "9:00 - 21:00" },
      { day: "土", time: "9:00 - 21:00" },
      { day: "日", time: "9:00 - 21:00" },
    ],
    features: ["完全予約制・基本無人営業", "初心者/中上級でクラス分離", "駐車場4台"],
    lessons: {
      available: true,
      types: ["バク転", "バク宙", "体操", "チアリーディング", "マット運動基礎", "トリッキング"],
      schedule: "9:00〜21:00（完全予約制）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["Web予約"], leadTime: "予約時間5分前から入室" },
  },
  {
    id: "f66",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "パルクールスクール幕張",
    nameJa: "パルクールスクール幕張",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "千葉県千葉市美浜区豊砂1-6",
    area: "千葉 / 千葉市",
    distance: 32.3,
    lat: 35.6121,
    lng: 140.1142,
    tags: ["パルクール", "キッズ専門", "イオンモール幕張"],
    description:
      "イオンモール幕張新都心内のパルクール専門スクール。約40坪のパルクールエリアで、6〜12歳が国際資格を持つコーチの指導でバランス・跳躍・登攀などを学ぶ。",
    photos: [{ label: "パルクールスクール幕張 — 写真準備中", color: "ok-slate" }],
    links: { web: "https://www.parkour-school.jp/place/makuhari", instagram: "@parkourschool_makuhari" },
    features: ["6〜12歳対象", "約40坪のパルクールエリア", "国際資格を持つコーチ", "イオンモール内"],
    lessons: {
      available: true,
      types: ["パルクール基礎（キッズ）"],
      schedule: "予約制（hacomono）",
      price: "要問い合わせ",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["オンライン予約（hacomono）"],
      leadTime: "—",
    },
  },
  {
    id: "f67",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "アスレチック ジム エクシード",
    nameJa: "アスレチックジム エクシード",
    type: "parkour",
    typeLabel: "パルクール",
    address: "愛知県春日井市鳥居松町4-96",
    area: "愛知 / 春日井市",
    distance: 253,
    lat: 35.3002,
    lng: 137.008,
    tags: ["アクロバット", "ブレイキン", "パルクール"],
    description:
      "アクロバット・ブレイキン・パルクール・ピラティスの運動スクール。子どもから大人まで、一人ひとりのペースに合わせて指導する。",
    photos: [{ label: "アスレチック ジム エクシード — 写真準備中", color: "ok-lime" }],
    links: { web: "https://www.athleticgymexceed.com/", instagram: "@athletic_gym_exceed" },
    phone: "090-7311-3055",
    features: ["キッズ〜大人対応", "アクロ/ブレイキン/パルクール/ピラティス", "挑戦できる心と動ける身体を育てる"],
    lessons: {
      available: true,
      types: ["アクロバット教室", "ブレイキン教室", "パルクール教室", "おとなアクロ", "ピラティスパーソナル"],
      schedule: "予約制（Googleフォーム / Square / 電話）",
      price: "要問い合わせ",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["Googleフォーム", "Square予約", "電話"],
      leadTime: "—",
    },
  },
  {
    id: "f68",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Dojo Parkour",
    nameJa: "道場パルクール",
    type: "parkour",
    typeLabel: "パルクール",
    address: "愛知県岡崎市羽根町小豆坂3",
    area: "愛知 / 岡崎市",
    distance: 251,
    lat: 34.9729,
    lng: 137.1436,
    tags: ["パルクール", "岡崎市"],
    description: "岡崎市のパルクール施設。",
    photos: [{ label: "Dojo Parkour — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.studiowing-hp.com/parkour" },
  },
  {
    id: "f69",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "高岡公園体育館パルクール教室",
    nameJa: "高岡公園体育館パルクール教室",
    type: "parkour",
    typeLabel: "パルクール",
    address: "愛知県豊田市中田町川向8",
    area: "愛知 / 豊田市",
    distance: 247,
    lat: 35.1831,
    lng: 137.1149,
    tags: ["パルクール", "豊田市"],
    description: "豊田市のパルクール施設。",
    photos: [{ label: "高岡公園体育館パルクール教室 — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f70",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Mr.JUMP 扶桑店パルクール教室",
    nameJa: "ミスタージャンプ 扶桑",
    type: "parkour",
    typeLabel: "パルクール",
    address: "愛知県丹羽郡扶桑町南山名",
    area: "愛知 / 扶桑町",
    distance: 261,
    lat: 35.3682,
    lng: 136.9057,
    tags: ["トランポリン", "ボルダリング", "扶桑町"],
    description:
      "扶桑町の複合アスレチック施設Mr.JUMP。トランポリンパークやボルダリングを備え、パルクール教室も開講する。",
    photos: [{ label: "Mr.JUMP 扶桑店パルクール教室 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://mrjump.jp/fuso/" },
    phone: "0587-91-3922",
    equipment: ["トランポリン", "ボルダリング"],
    features: ["複合アスレチック施設", "家族向け"],
    lessons: {
      available: true,
      types: ["パルクール教室"],
      schedule: "電話予約",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["電話予約"], leadTime: "—" },
  },
  {
    id: "f71",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "一宮パルクール教室",
    nameJa: "一宮パルクール教室",
    type: "parkour",
    typeLabel: "パルクール",
    address: "愛知県一宮市萩原町",
    area: "愛知 / 一宮市",
    distance: 275,
    lat: 35.2751,
    lng: 136.7725,
    tags: ["パルクール", "一宮市"],
    description: "一宮市のパルクール施設。",
    photos: [{ label: "一宮パルクール教室 — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.nagoyaparkour.com/" },
    image: "https://image.jimcdn.com/app/cms/image/transf/dimension=1920x10000:format=jpg/path/s9a3bc00610e9b3c1/image/i3e2992f25f3b955b/version/1705479167/image.jpg",
  },
  {
    id: "f72",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Mr.JUMP 守山店パルクール教室",
    nameJa: "ミスタージャンプ 守山",
    type: "parkour",
    typeLabel: "パルクール",
    address: "愛知県名古屋市守山区大永寺町142",
    area: "愛知 / 名古屋市",
    distance: 265,
    lat: 35.183,
    lng: 136.9026,
    tags: ["トランポリン", "ボルダリング", "名古屋市"],
    description:
      "名古屋・守山の複合アスレチック施設Mr.JUMP。トランポリンパークやボルダリングを備え、パルクール教室も開講する。",
    photos: [{ label: "Mr.JUMP 守山店パルクール教室 — 写真準備中", color: "ok-slate" }],
    links: { web: "https://mrjump.jp/moriyama/" },
    phone: "052-778-9190",
    equipment: ["トランポリン", "ボルダリング", "ウォールトランポリン"],
    features: ["複合アスレチック施設", "家族向け"],
    lessons: {
      available: true,
      types: ["パルクール教室"],
      schedule: "プライベート(電話) / フリー(WEB予約)",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["電話予約", "WEB予約(eipro)"], leadTime: "—" },
  },
  {
    id: "f73",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "ガンバデパルクール教室",
    nameJa: "ガンバデパルクール教室",
    type: "parkour",
    typeLabel: "パルクール",
    address: "愛知県名古屋市中川区供米田2",
    area: "愛知 / 名古屋市",
    distance: 265,
    lat: 35.183,
    lng: 136.9026,
    tags: ["パルクール", "名古屋市"],
    description: "名古屋市のパルクール施設。",
    photos: [{ label: "ガンバデパルクール教室 — 写真準備中", color: "ok-lime" }],
    links: {},
  },
  {
    id: "f74",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "REALIZE 札幌パルクール教室",
    nameJa: "リアライズ 札幌パルクール",
    type: "parkour",
    typeLabel: "パルクール",
    address: "北海道札幌市西区琴似1条4-1-29",
    area: "北海道 / 札幌市",
    distance: 833,
    lat: 43.0761,
    lng: 141.3048,
    tags: ["パルクール", "札幌市"],
    description: "札幌市のパルクール施設。",
    photos: [{ label: "REALIZE 札幌パルクール教室 — 写真準備中", color: "ok-amber" }],
    links: { web: "https://jokercrewpk.wixsite.com/realize-pk-school", instagram: "@parkour_realize_sapporo" },
  },
  {
    id: "f75",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "GaGa Hypes",
    nameJa: "ガガ ハイプス",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "兵庫県加東市社1126-1",
    area: "兵庫 / 加東市",
    distance: 440,
    lat: 34.9125,
    lng: 135.016,
    tags: ["総合", "加東市"],
    description: "加東市のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "GaGa Hypes — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f76",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "神戸アクロバットスタジオ タンドラ 阪神春日野道店",
    nameJa: "タンドラ 春日野道",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "兵庫県神戸市中央区南本町通1-1-1",
    area: "兵庫 / 神戸市",
    distance: 433,
    lat: 34.6679,
    lng: 135.1641,
    tags: ["バック転", "タンブリング", "未経験歓迎"],
    description:
      "神戸・春日野道のアクロバットスタジオ。全面タンブリングバーンと体操競技用の特殊床を備え、未経験者歓迎でバック転・アクロバット・トリッキングを練習できる。",
    photos: [{ label: "神戸アクロバットスタジオ タンドラ 阪神春日野道店 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://www.tumdra.com/", instagram: "@tum_dra" },
    image: "https://www.tumdra.com/img/base/ogp.jpg",
    phone: "078-203-4307",
    equipment: ["全面タンブリングバーン", "体操競技用特殊床（スプリング床）", "空調完備"],
    hours: [
      { day: "月", time: "12:00 - 22:00" },
      { day: "火", time: "12:00 - 22:00" },
      { day: "水", time: "12:00 - 22:00" },
      { day: "木", time: "12:00 - 22:00" },
      { day: "金", time: "12:00 - 22:00" },
      { day: "土", time: "12:00 - 22:00" },
      { day: "日", time: "12:00 - 22:00" },
    ],
    features: ["神戸初のアクロバットスタジオ", "未経験者大歓迎", "個人のペースで指導"],
    lessons: {
      available: true,
      types: ["バック転", "アクロバット", "トリッキング"],
      schedule: "12:00〜22:00",
      price: "体験あり（スポーツ保険 幼児・小学生¥1,000 / 中学生以上¥2,000）",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["オンライン予約フォーム", "お問い合わせ"],
      leadTime: "—",
    },
  },
  {
    id: "f77",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "神戸アクロバットスタジオ タンドラ2 御崎公園店",
    nameJa: "タンドラ2 御崎公園",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "兵庫県神戸市兵庫区浜中町1-17-1",
    area: "兵庫 / 神戸市",
    distance: 433,
    lat: 34.6679,
    lng: 135.1641,
    tags: ["バック転", "タンブリング", "未経験歓迎"],
    description:
      "神戸・御崎公園のアクロバットスタジオ。タンドラ系列の2号店で、全面タンブリングバーンを備え未経験者歓迎でバック転・アクロバット・トリッキングを練習できる。",
    photos: [{ label: "神戸アクロバットスタジオ タンドラ2 御崎公園店 — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.tumdra.com/", instagram: "@tum_dra" },
    image: "https://www.tumdra.com/img/base/ogp.jpg",
    phone: "078-335-6255",
    equipment: ["全面タンブリングバーン", "体操競技用特殊床（スプリング床）", "空調完備"],
    features: ["神戸初のアクロバットスタジオ系列", "未経験者大歓迎", "個人のペースで指導"],
    lessons: {
      available: true,
      types: ["バック転", "アクロバット", "トリッキング"],
      schedule: "予約制",
      price: "体験あり（スポーツ保険 幼児・小学生¥1,000 / 中学生以上¥2,000）",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["オンライン予約フォーム", "お問い合わせ"],
      leadTime: "—",
    },
  },
  {
    id: "f78",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "おさるの森 スタジオ",
    nameJa: "おさるの森スタジオ",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "兵庫県姫路市大津区平松317-5",
    area: "兵庫 / 姫路市",
    distance: 470,
    lat: 34.8264,
    lng: 134.702,
    tags: ["総合", "姫路市"],
    description: "姫路市のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "おさるの森 スタジオ — 写真準備中", color: "ok-slate" }],
    links: { web: "https://osaru.fun/parkour", instagram: "@osarunomori.jp" },
  },
  {
    id: "f79",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "FPC PARKOUR CLASS",
    nameJa: "エフピーシー パルクールクラス",
    type: "parkour",
    typeLabel: "パルクール",
    address: "福岡県春日市原町3-1-4",
    area: "福岡 / 春日市",
    distance: 883,
    lat: 33.5326,
    lng: 130.47,
    tags: ["パルクール", "キッズ〜大人", "国際資格コーチ"],
    description:
      "春日市のパルクール教室。国際指導資格を持つコーチが、キッズ（6〜12歳）から大人（13歳〜）まで基礎から安全に指導する。",
    photos: [{ label: "FPC PARKOUR CLASS — 写真準備中", color: "ok-lime" }],
    links: {
      web: "https://class.fukuoka-parkour-connection.com/",
      twitter: "@FukuParConnect",
      instagram: "@fpcparkourclass",
    },
    image: "https://class.fukuoka-parkour-connection.com/ogp.png",
    payment: ["現金"],
    features: ["国際指導資格のコーチ", "経験不問", "キッズ・大人・パーソナル"],
    lessons: {
      available: true,
      types: ["キッズクラス（6〜12歳）", "大人クラス（13歳〜）", "パーソナルレッスン"],
      schedule: "予約制（雨天中止）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["お問い合わせフォーム"], leadTime: "—" },
  },
  {
    id: "f80",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "ジャングルジム",
    nameJa: "ジャングルジム",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "静岡県藤枝市鬼島528-6",
    area: "静岡 / 藤枝市",
    distance: 164,
    lat: 34.8674,
    lng: 138.2577,
    tags: ["パルクール", "キッズ", "レベル認定制"],
    description:
      "藤枝市のパルクールフィットネス施設。レベル認定制度を設け、小学生のキッズクラスから大人まで楽しさを重視して指導する。",
    photos: [{ label: "ジャングルジム — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.junglegym81.com/", instagram: "@junglegym81" },
    features: ["レベル認定制度あり", "キッズクラスあり", "楽しさを追求"],
    lessons: {
      available: true,
      types: ["パルクールフィットネス", "キッズクラス（小学生）"],
      schedule: "オンライン予約 / LINE",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["オンライン予約", "公式LINE"], leadTime: "—" },
  },
  {
    id: "f81",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Köln",
    nameJa: "ケルン",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "広島県安芸郡坂町坂東1-2-16",
    area: "広島 / 安芸郡坂町",
    distance: 677,
    lat: 34.3413,
    lng: 132.5136,
    tags: ["パルクール", "初心者〜アスリート", "カフェ併設"],
    description:
      "広島・坂町のパルクール施設。選手権出場経験のあるインストラクターが初心者からアスリートまで指導し、ダンス・ヨガも開講。カフェスペースも備える。",
    photos: [{ label: "Köln — 写真準備中", color: "ok-slate" }],
    links: { web: "https://kolnhiroshima.com/", instagram: "@koln_hiroshima" },
    image: "https://kolnhiroshima.com/common/upload_data/kolnhiroshimacom/image/20250120104121.jpg",
    phone: "082-824-8996",
    equipment: ["カフェスペース", "更衣室", "駐車場8台", "Wi-Fi"],
    hours: [
      { day: "月", time: "10:00 - 21:00" },
      { day: "火", time: "10:00 - 21:00" },
      { day: "水", time: "10:00 - 21:00" },
      { day: "木", time: "10:00 - 21:00" },
      { day: "金", time: "10:00 - 21:00" },
      { day: "土", time: "10:00 - 21:00" },
      { day: "日", time: "10:00 - 21:00" },
    ],
    payment: ["口座振替"],
    features: ["選手権出場経験のインストラクター", "初心者〜アスリート対応", "ダンス・ヨガも開講", "公共交通アクセス良好"],
    lessons: {
      available: true,
      types: ["パルクール（初心者）", "パルクール（アスリート）", "ダンス", "ヨガ"],
      schedule: "本店 10:00〜21:00",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["お問い合わせフォーム", "電話"], leadTime: "—" },
  },
  {
    id: "f82",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "広テレ!キャンパス",
    nameJa: "広テレ!キャンパス",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "広島県広島市東区二葉の里3-5-4",
    area: "広島 / 広島市",
    distance: 679,
    lat: 34.3974,
    lng: 132.476,
    tags: ["総合", "広島市"],
    description: "広島市のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "広テレ!キャンパス — 写真準備中", color: "ok-lime" }],
    links: {},
  },
  {
    id: "f83",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "リッチコンタクト",
    nameJa: "リッチコンタクト",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "広島県広島市西区草津南2-4-7",
    area: "広島 / 広島市",
    distance: 679,
    lat: 34.3974,
    lng: 132.476,
    tags: ["パルクール", "トリッキング", "親子参加可"],
    description:
      "広島・西区の次世代の習い事パーク。パルクール・トリッキング・アクロバットに加え書道も学べ、カフェ・オープンジム・レンタルスペースを備える。",
    photos: [{ label: "リッチコンタクト — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.richcontact.net/home", instagram: "@rich_contact" },
    price: "体験 初回無料 / 2回目以降 ¥1,000",
    priceDay: "年会費 ¥10,000（キャンペーン ¥5,000）・夏期講習 4日¥13,000〜",
    features: ["パルクール/トリッキング/アクロバット/書道", "カフェ・オープンジム・レンタルスペース", "親子参加可", "東広島店・住吉店あり"],
    lessons: {
      available: true,
      types: ["パルクール", "トリッキング", "アクロバット", "書道"],
      schedule: "無料体験会あり",
      price: "体験 初回無料 / 2回目¥1,000",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["電話", "メール", "Instagram DM", "Googleフォーム"],
      leadTime: "—",
    },
    image: "https://static.wixstatic.com/media/2bf63c_085b56f286f042bf8b30871dc1b446af~mv2.jpg/v1/fill/w_2500,h_1768,al_c/2bf63c_085b56f286f042bf8b30871dc1b446af~mv2.jpg",
  },
  {
    id: "f84",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "JUMP&LEAP",
    nameJa: "ジャンプ&リープ",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "宮城県黒川郡大和町小野馬場94-4",
    area: "宮城 / 大和町",
    distance: 322,
    lat: 38.4374,
    lng: 140.8861,
    tags: ["パルクール", "会員制", "教育型"],
    description:
      "宮城・大和町の教育型会員制パルクール教室。挑戦する力・考える力・自信を育てることを目的に、小1から高校生、競技志向まで段階別に指導する。",
    photos: [{ label: "JUMP&LEAP — 写真準備中", color: "ok-slate" }],
    links: { web: "https://www.jump-leap.com/", instagram: "@jump.leap", twitter: "@jumpleap1" },
    phone: "080-7216-1382",
    price: "月額 ¥13,990（税込）",
    hours: [
      { day: "月", time: "定休日", closed: true },
      { day: "火", time: "定休日", closed: true },
      { day: "水", time: "15:00 - 21:00" },
      { day: "木", time: "15:00 - 21:00" },
      { day: "金", time: "15:00 - 21:00" },
      { day: "土", time: "10:00 - 18:00" },
      { day: "日", time: "10:00 - 18:00" },
    ],
    features: ["教育型・会員制", "段階別クラス（小1〜競技志向）", "安全管理を徹底", "自由練習あり"],
    lessons: {
      available: true,
      types: ["スタートアップ（小1〜3）", "きほん（小4〜高校生）", "アスリート（選抜制）", "自由練習"],
      schedule: "平日15:00〜21:00 / 土日10:00〜18:00（月火休）",
      price: "月額 ¥13,990",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["トライアル予約フォーム", "見学フォーム"],
      leadTime: "—",
    },
    image: "https://static.wixstatic.com/media/dacef8_005311384a7f49739bcd6b74a6fcbc30%7Emv2.png/v1/fit/w_2500,h_1330,al_c/dacef8_005311384a7f49739bcd6b74a6fcbc30%7Emv2.png",
  },
  {
    id: "f85",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "studio LAVISH",
    nameJa: "スタジオ ラヴィッシュ",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "茨城県土浦市港町1-4-22",
    area: "茨城 / 土浦市",
    distance: 60.8,
    lat: 36.0982,
    lng: 140.2035,
    tags: ["アクロバット", "トリッキング", "出張対応"],
    description:
      "土浦市のアクロバット・トリッキング専門教室。バク転・マカコ・バタフライキック等を指導し、出張レッスンやイベント・メディア出演にも対応する。",
    photos: [{ label: "studio LAVISH — 写真準備中", color: "ok-lime" }],
    links: { web: "https://studio-tsuchiura.main.jp/" },
    features: ["アクロバット/トリッキング/パルクール", "宇都宮にも店舗", "メディア・イベント出演実績"],
    lessons: {
      available: true,
      types: ["アクロバット", "トリッキング", "パルクール", "出張レッスン"],
      schedule: "公式LINE / お問い合わせフォーム",
      price: "イベント出演 ¥20,000〜（レッスンは内容により変動）",
    },
    booking: {
      required: true,
      walkIn: false,
      methods: ["公式LINE", "お問い合わせフォーム"],
      leadTime: "—",
    },
  },
  {
    id: "f86",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "ニンジャパーク 古河店",
    nameJa: "ニンジャパーク 古河",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "茨城県古河市小堤",
    area: "茨城 / 古河市",
    distance: 59.1,
    lat: 36.2122,
    lng: 139.7635,
    tags: ["総合", "古河市"],
    description: "古河市のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "ニンジャパーク 古河店 — 写真準備中", color: "ok-amber" }],
    links: {},
  },
  {
    id: "f87",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "イオンスポーツクラブ 3FIT 小山店",
    nameJa: "3FIT 小山",
    type: "mixed",
    typeLabel: "総合スポーツ施設",
    address: "栃木県小山市中久喜1345-6",
    area: "栃木 / 小山市",
    distance: 71.5,
    lat: 36.3234,
    lng: 139.7927,
    tags: ["総合", "小山市"],
    description: "小山市のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "イオンスポーツクラブ 3FIT 小山店 — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f88",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "岐阜パルクール教室",
    nameJa: "岐阜パルクール教室",
    type: "parkour",
    typeLabel: "パルクール",
    address: "岐阜県岐阜市薮田南2-1-1",
    area: "岐阜 / 岐阜市",
    distance: 277,
    lat: 35.3912,
    lng: 136.7245,
    tags: ["パルクール", "年少〜大人", "SPEMON講師"],
    description:
      "岐阜市・ぎふ清流アリーナの岐阜県初のパルクール定期教室。プロチームSPEMONの講師が、年少から大人まで初心者・経験者別に指導する。",
    photos: [{ label: "岐阜パルクール教室 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://gifu-arena.dolphin-group.co.jp/kids/parkour" },
    image: "https://gifu-arena.dolphin-group.co.jp/wp/wp-content/themes/gifu-arena/common/images/ogImg.png",
    phone: "058-272-1336",
    price: "体験 ¥1,100",
    priceDay: "月2会員 ¥4,400〜5,500 / ONE会員 ¥8,250 ・ 入会手数料 ¥5,500",
    hours: [
      { day: "月", time: "9:00 - 21:00" },
      { day: "火", time: "9:00 - 21:00" },
      { day: "水", time: "9:00 - 21:00" },
      { day: "木", time: "9:00 - 21:00" },
      { day: "金", time: "9:00 - 21:00" },
      { day: "土", time: "9:00 - 21:00" },
      { day: "日", time: "9:00 - 21:00" },
    ],
    features: ["岐阜県初のパルクール定期教室", "プロチームSPEMON講師", "年少〜大人", "火・水・土開講"],
    lessons: {
      available: true,
      types: ["エントリー（年少〜年長）", "スターター（初心者）", "ベーシック（経験者）"],
      schedule: "火・水・土曜開講",
      price: "体験 ¥1,100 / 月2 ¥4,400〜",
    },
    booking: { required: true, walkIn: false, methods: ["電話", "お問い合わせフォーム"], leadTime: "—" },
  },
  {
    id: "f89",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "アクロバットダンススタジオ",
    nameJa: "アクロバットダンススタジオ",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "奈良県生駒市辻町390-1",
    area: "奈良 / 生駒市",
    distance: 381,
    lat: 34.7318,
    lng: 135.7336,
    tags: ["アクロバットダンス", "キッズ", "幼児クラス"],
    description:
      "生駒市のアクロバットダンス専門スタジオ。幼児（4〜6歳）クラスから一般まで、複数会場でアクロバット＆ダンスを指導する。",
    photos: [{ label: "アクロバットダンススタジオ — 写真準備中", color: "ok-amber" }],
    links: { web: "https://acrobatdancestudio.wixsite.com/ikoma", instagram: "@adsacrobat" },
    phone: "080-8127-0514",
    features: ["幼児（4〜6歳）クラスあり", "見学無料", "複数会場で開講"],
    lessons: {
      available: true,
      types: ["幼児クラス（4〜6歳）", "一般クラス"],
      schedule: "会場により異なる（見学・体験受付中）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["お問い合わせフォーム"], leadTime: "—" },
  },
  {
    id: "f90",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Old Schoolers",
    nameJa: "オールドスクーラーズ",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "三重県桑名市西方",
    area: "三重 / 桑名市",
    distance: 289,
    lat: 35.0664,
    lng: 136.6685,
    tags: ["ブレイクダンス", "アクロバット", "少人数制"],
    description:
      "桑名市のブレイクダンス・アクロバット教室。バク転・バク宙・ロンダート・側宙などを、子どもから大人まで少人数制で指導する。",
    photos: [{ label: "Old Schoolers — 写真準備中", color: "ok-slate" }],
    links: { web: "https://lockandbreak.wixsite.com/oldschoolers" },
    price: "入会金 ¥6,600（6月まで ¥3,300）",
    features: ["少人数制レッスン", "ブレイクダンス＆アクロバット", "プロ志向も受け入れ"],
    lessons: {
      available: true,
      types: ["ブレイクダンス", "アクロバット（バク転・バク宙・ロンダート・側宙）"],
      schedule: "体験レッスン予約受付中",
      price: "入会金 ¥6,600（6月まで ¥3,300）",
    },
    booking: { required: true, walkIn: false, methods: ["お問い合わせ"], leadTime: "—" },
  },
  {
    id: "f91",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "熊本玉名パルクール協会",
    nameJa: "熊本玉名パルクール協会",
    type: "parkour",
    typeLabel: "パルクール",
    address: "熊本県玉名市伊倉北方2636",
    area: "熊本 / 玉名市",
    distance: 897,
    lat: 32.9349,
    lng: 130.5796,
    tags: ["パルクール", "ボルダリング", "初心者対応"],
    description:
      "玉名市のパルクール協会。玉南中・大津の森体育館やレアスポーツパーク（パルクール・ボルダリング・スラックライン）で、子どもから大人まで道具不要で指導する。",
    photos: [{ label: "熊本玉名パルクール協会 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://parkour-kumatama.jimdofree.com/" },
    price: "体験会 ¥500 / イベント ¥1,000",
    priceDay: "レアスポーツパークは回数券（チケット制）",
    equipment: ["体育館（屋内）", "レアスポーツパーク（パルクール/ボルダリング/スラックライン）"],
    features: ["道具不要・年齢性別不問", "初心者対応", "メンタルトレーニング重視"],
    lessons: {
      available: true,
      types: ["定期体験教室（金・土）", "常設 RARE SPORTS LAB 2.0（月・火・木）", "出前体験・講座", "イベント"],
      schedule: "金20:00〜21:30 / 土19:00〜20:30 / 常設は月・火・木",
      price: "体験 ¥500 / イベント ¥1,000",
    },
    booking: { required: true, walkIn: false, methods: ["予約フォーム", "メール"], leadTime: "—" },
    image: "https://image.jimcdn.com/app/cms/image/transf/dimension=1920x10000:format=png/path/sf8e6360cf145228b/image/i9556348b52d53986/version/1778164991/image.png",
  },
  {
    id: "f92",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "SSS KUMAMOTO",
    nameJa: "エスエスエス熊本",
    type: "mixed",
    typeLabel: "総合アクロバット",
    address: "熊本県熊本市東区御領6-2-19",
    area: "熊本 / 熊本市",
    distance: 894,
    lat: 32.7903,
    lng: 130.689,
    tags: ["総合", "熊本市"],
    description: "熊本市のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "SSS KUMAMOTO — 写真準備中", color: "ok-amber" }],
    links: { instagram: "@sss_kumamoto" },
  },
  {
    id: "f93",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Do Challenge Club 健軍店",
    nameJa: "ドゥチャレンジクラブ 健軍",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "熊本県熊本市東区若葉1-31-8",
    area: "熊本 / 熊本市",
    distance: 894,
    lat: 32.7903,
    lng: 130.689,
    tags: ["体操", "トランポリン", "九州最大級"],
    description:
      "熊本市・健軍のスポーツクラブ。九州最大級・在籍2,000名超で、14m角のバネ付きフロアと埋め込みトランポリンを備え、体操・アクロバット・パルクール・トリッキング等を指導する。",
    photos: [{ label: "Do Challenge Club 健軍店 — 写真準備中", color: "ok-slate" }],
    links: { web: "https://dochallengeclub.net/", instagram: "@dochallengeclub" },
    image: "https://dochallengeclub.net/wp/wp-content/uploads/2021/11/og-image-1.jpg",
    phone: "096-273-8361",
    equipment: ["14m×14mバネ付きフロア", "埋め込み式トランポリン", "音響・照明設備"],
    hours: [
      { day: "月", time: "12:00 - 22:00" },
      { day: "火", time: "12:00 - 22:00" },
      { day: "水", time: "12:00 - 22:00" },
      { day: "木", time: "12:00 - 22:00" },
      { day: "金", time: "12:00 - 22:00" },
      { day: "土", time: "12:00 - 21:00" },
      { day: "日", time: "定休日", closed: true },
    ],
    payment: ["銀行振込", "口座振替"],
    features: ["九州最大級・在籍2,000名超", "競技出身者による指導", "安全面に配慮"],
    lessons: {
      available: true,
      types: ["体操", "アクロバット", "ダンス", "パルクール", "トリッキング", "3×3バスケ", "スケートボード", "マンツーマン"],
      schedule: "平日12:00〜22:00 / 土12:00〜21:00（日祝休）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["WEB予約", "電話"], leadTime: "—" },
  },
  {
    id: "f94",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Do Challenge Club 武蔵ヶ丘",
    nameJa: "ドゥチャレンジクラブ 武蔵ヶ丘",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "熊本県菊池郡菊陽町武蔵ヶ丘2-9-12",
    area: "熊本 / 菊陽町",
    distance: 875,
    lat: 32.8858,
    lng: 130.8613,
    tags: ["体操", "トランポリン", "九州最大級"],
    description:
      "菊陽町・武蔵ヶ丘のスポーツクラブ。九州最大級Do Challenge Clubの系列で、体操・アクロバット・パルクール・トリッキング等を競技出身者が指導する。",
    photos: [{ label: "Do Challenge Club 武蔵ヶ丘 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://dochallengeclub.net/", instagram: "@dochallengeclub" },
    image: "https://dochallengeclub.net/wp/wp-content/uploads/2021/11/og-image-1.jpg",
    phone: "096-273-8361",
    equipment: ["バネ付きフロア", "埋め込み式トランポリン", "音響・照明設備"],
    payment: ["銀行振込", "口座振替"],
    features: ["九州最大級Do Challenge Club系列", "競技出身者による指導", "安全面に配慮"],
    lessons: {
      available: true,
      types: ["体操", "アクロバット", "ダンス", "パルクール", "トリッキング", "マンツーマン"],
      schedule: "平日12:00〜22:00 / 土12:00〜21:00（日祝休）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["WEB予約", "電話"], leadTime: "—" },
  },
  {
    id: "f95",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Do Challenge Club 小山本店",
    nameJa: "ドゥチャレンジクラブ 小山本店",
    type: "mixed",
    typeLabel: "アクロバット",
    address: "熊本県熊本市東区小山2-13-15",
    area: "熊本 / 熊本市",
    distance: 894,
    lat: 32.7903,
    lng: 130.689,
    tags: ["体操", "トランポリン", "九州最大級"],
    description:
      "熊本市・小山の本店。九州最大級・在籍2,000名超のスポーツクラブで、14m角のバネ付きフロアと埋め込みトランポリンを備え、体操・アクロバット・パルクール等を指導する。",
    photos: [{ label: "Do Challenge Club 小山本店 — 写真準備中", color: "ok-amber" }],
    links: { web: "https://dochallengeclub.net/", instagram: "@dochallengeclub" },
    image: "https://dochallengeclub.net/wp/wp-content/uploads/2021/11/og-image-1.jpg",
    phone: "096-273-8361",
    equipment: ["14m×14mバネ付きフロア", "埋め込み式トランポリン", "音響・照明設備"],
    hours: [
      { day: "月", time: "12:00 - 22:00" },
      { day: "火", time: "12:00 - 22:00" },
      { day: "水", time: "12:00 - 22:00" },
      { day: "木", time: "12:00 - 22:00" },
      { day: "金", time: "12:00 - 22:00" },
      { day: "土", time: "12:00 - 21:00" },
      { day: "日", time: "定休日", closed: true },
    ],
    payment: ["銀行振込", "口座振替"],
    features: ["九州最大級・在籍2,000名超", "競技出身者による指導", "本店"],
    lessons: {
      available: true,
      types: ["体操", "アクロバット", "ダンス", "パルクール", "トリッキング", "3×3バスケ", "スケートボード", "マンツーマン"],
      schedule: "平日12:00〜22:00 / 土12:00〜21:00（日祝休）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["WEB予約", "電話"], leadTime: "—" },
  },
  {
    id: "f96",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "Parkour Gym CASTHOUSE",
    nameJa: "パルクールジム キャストハウス",
    type: "parkour",
    typeLabel: "パルクール",
    address: "石川県金沢市神宮寺3-9-20",
    area: "石川 / 金沢市",
    distance: 296,
    lat: 36.5616,
    lng: 136.6569,
    tags: ["パルクール", "金沢市"],
    description: "金沢市のパルクール施設。",
    photos: [{ label: "Parkour Gym CASTHOUSE — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f97",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "香川県パルクール教室 丸亀教室",
    nameJa: "香川パルクール 丸亀",
    type: "parkour",
    typeLabel: "パルクール",
    address: "香川県丸亀市金倉町830",
    area: "香川 / 丸亀市",
    distance: 565,
    lat: 34.2888,
    lng: 133.7982,
    tags: ["パルクール", "初心者〜経験者", "丸亀市"],
    description:
      "丸亀市のパルクール教室。香川県を拠点とするコミュニティ『讃岐パルクールサイト』が、丸亀競技場（Pikaraスタジアム）で初心者〜経験者向けに開催する。",
    photos: [{ label: "香川県パルクール教室 丸亀教室 — 写真準備中", color: "ok-lime" }],
    links: { web: "https://www.sanukipksight.com/", instagram: "@kagawa_pk_class" },
    features: ["香川拠点のパルクールコミュニティ", "初心者〜経験者", "競技場で開催"],
    lessons: {
      available: true,
      types: ["まるがめ教室", "パルクール練習会/JAM", "出張体験・ショー"],
      schedule: "予約制（Pikaraスタジアム窓口）",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["Pikaraスタジアム窓口", "電話"], leadTime: "—" },
    image: "https://static.wixstatic.com/media/14d10f_938a373e4095400aacbba10da9fee28a~mv2.png/v1/fill/w_2500,h_3534,al_c/14d10f_938a373e4095400aacbba10da9fee28a~mv2.png",
  },
  {
    id: "f98",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "香川県パルクール教室 屋島教室",
    nameJa: "香川パルクール 屋島",
    type: "parkour",
    typeLabel: "パルクール",
    address: "香川県高松市新田町甲393-6",
    area: "香川 / 高松市",
    distance: 542,
    lat: 34.3426,
    lng: 134.0465,
    tags: ["パルクール", "初心者〜経験者", "高松市"],
    description:
      "高松市・屋島のパルクール教室。香川県拠点のコミュニティ『讃岐パルクールサイト』が運営するパルクールジム UNLEASH KAGAWA を中心に、初心者〜経験者向けに開催する。",
    photos: [{ label: "香川県パルクール教室 屋島教室 — 写真準備中", color: "ok-amber" }],
    links: { web: "https://www.sanukipksight.com/", instagram: "@unleash_kagawa" },
    features: ["香川拠点のパルクールコミュニティ", "初心者〜経験者", "予約制ジムあり"],
    lessons: {
      available: true,
      types: ["パルクールジム UNLEASH KAGAWA", "練習会/JAM", "出張体験・ショー"],
      schedule: "予約制",
      price: "要問い合わせ",
    },
    booking: { required: true, walkIn: false, methods: ["予約ページ", "Instagram"], leadTime: "—" },
    image: "https://static.wixstatic.com/media/14d10f_938a373e4095400aacbba10da9fee28a~mv2.png/v1/fill/w_2500,h_3534,al_c/14d10f_938a373e4095400aacbba10da9fee28a~mv2.png",
  },
  {
    id: "f99",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "周南総合スポーツセンター",
    nameJa: "周南総合スポーツセンター",
    type: "mixed",
    typeLabel: "総合スポーツ施設",
    address: "山口県周南市徳山10427",
    area: "山口 / 周南市",
    distance: 748,
    lat: 34.0551,
    lng: 131.8064,
    tags: ["総合", "周南市"],
    description: "周南市のパルクール・トリッキング・アクロバット施設。",
    photos: [{ label: "周南総合スポーツセンター — 写真準備中", color: "ok-slate" }],
    links: {},
  },
  {
    id: "f100",
    registeredAt: "2026-05-21",
    updatedAt: "2026-05-21",
    name: "パルクールガーデン",
    nameJa: "パルクールガーデン",
    type: "parkour",
    typeLabel: "パルクール",
    address: "鹿児島県鹿児島市",
    area: "鹿児島 / 鹿児島市",
    distance: 965,
    lat: 31.5968,
    lng: 130.5572,
    tags: ["パルクール", "鹿児島市"],
    description: "鹿児島市のパルクール施設。",
    photos: [{ label: "パルクールガーデン — 写真準備中", color: "ok-lime" }],
    links: {},
  },
];

export const EQUIPMENT_FILTERS: EquipmentFilter[] = [
  { key: "トランポリン", icon: "■" },
  { key: "フォームピット", icon: "◉" },
  { key: "オブスタクル", icon: "▤" },
  { key: "マット", icon: "▢" },
  { key: "レール", icon: "│" },
  { key: "タンブリング", icon: "▬" },
];

export const TYPE_FILTERS: TypeFilter[] = [
  { key: "all", label: "すべて" },
  { key: "tricking", label: "トリッキング" },
  { key: "parkour", label: "パルクール" },
  { key: "mixed", label: "総合" },
];
