// 6ジャンル80技のスキルデータ。
// 難易度 lv: 1（基礎）〜10（エリート）。prereqs / leads は技idの配列。

export type SkillGenre = "tricking" | "parkour" | "gym" | "break" | "ski" | "snow";

export interface Skill {
  id: string;
  genre: SkillGenre;
  name_ja: string;
  name_en: string;
  lv: number;
  tags: string[];
  desc_ja: string;
  desc_en: string;
  tips_ja: string[];
  prereqs: string[];
  leads: string[];
}

export interface SkillGenreDef {
  id: "all" | SkillGenre;
  name_ja: string;
  name_en: string;
  abbr: string;
}

export const SKILLS: Skill[] = [
  // ─────────── TRICKING (14) ───────────
  { id: "round-off", genre: "tricking", name_ja: "ラウンドオフ", name_en: "Round-off", lv: 2, tags: ["basic", "rotation"], desc_ja: "側転から両足同時着地へつなぐ加速技。多くのバック系の入り口。", desc_en: "A cartwheel that lands on two feet — gateway to backward tumbling.", tips_ja: ["手のつき位置を一直線上に", "後ろ足を真上に蹴り上げる", "着地時にお尻を前に出す"], prereqs: [], leads: ["back-handspring", "back-tuck"] },
  { id: "back-tuck", genre: "tricking", name_ja: "バックタック", name_en: "Back Tuck", lv: 4, tags: ["flip", "backward"], desc_ja: "後方宙返り（抱え込み）。トリッキングのコア。", desc_en: "Backward somersault in tuck position.", tips_ja: ["真上に跳ぶ意識", "膝を胸に強く引き寄せる", "視線で空中の回転を制御"], prereqs: ["round-off"], leads: ["back-full", "gainer"] },
  { id: "back-full", genre: "tricking", name_ja: "バックフル", name_en: "Back Full", lv: 6, tags: ["flip", "twist"], desc_ja: "バックタック中に1回ひねりを加える複合技。", desc_en: "Back tuck with a full twist.", tips_ja: ["ひねりは頂点で開始", "片腕を強くラップ", "肩のラインで回す"], prereqs: ["back-tuck"], leads: [] },
  { id: "aerial", genre: "tricking", name_ja: "エアリアル", name_en: "Aerial", lv: 4, tags: ["no-hand", "sideways"], desc_ja: "手を着かないノーハンド側転。", desc_en: "No-handed cartwheel.", tips_ja: ["前足の踏み込みを強く", "後ろ足を真上に振り上げる", "目線は床に残す"], prereqs: ["round-off"], leads: ["webster", "butterfly-twist"] },
  { id: "webster", genre: "tricking", name_ja: "ウェブスター", name_en: "Webster", lv: 4, tags: ["flip", "frontward"], desc_ja: "片足踏み切りの前方宙返り。", desc_en: "Single-leg front flip.", tips_ja: ["踏み切り脚を強くキック", "腕を上から下へ", "膝抱えのタイミング"], prereqs: ["round-off"], leads: ["loser", "snapuswipe"] },
  { id: "loser", genre: "tricking", name_ja: "ルーザー", name_en: "Loser", lv: 5, tags: ["flip", "frontward"], desc_ja: "後ろ足踏み切りの前方宙返り。ウェブスターの逆脚版。", desc_en: "Front flip off the back leg.", tips_ja: ["後ろ足の蹴り上げを意識", "上半身を投げ込まない", "視界で床を捉え続ける"], prereqs: ["webster"], leads: [] },
  { id: "butterfly-kick", genre: "tricking", name_ja: "バタフライキック", name_en: "Butterfly Kick", lv: 3, tags: ["kick", "spin"], desc_ja: "武術由来の横回転キック。トリッキング基礎。", desc_en: "Wushu-style horizontal spin kick.", tips_ja: ["上半身を地面に倒す", "腰から回す", "両脚を時間差で蹴る"], prereqs: [], leads: ["butterfly-twist"] },
  { id: "butterfly-twist", genre: "tricking", name_ja: "バタフライツイスト", name_en: "Butterfly Twist", lv: 6, tags: ["twist", "spin"], desc_ja: "バタフライキックに縦ひねりを加えた技。Bツイスト。", desc_en: "Butterfly kick with a vertical twist.", tips_ja: ["低く深いセットアップ", "上肩を地面に向ける", "ひねりは腰主導"], prereqs: ["butterfly-kick"], leads: [] },
  { id: "540-kick", genre: "tricking", name_ja: "540キック", name_en: "540 Kick", lv: 4, tags: ["kick", "spin"], desc_ja: "1回転半の蹴り技。", desc_en: "One-and-a-half rotation jump kick.", tips_ja: ["逆脚の蹴り上げで回転を作る", "蹴り脚は真っ直ぐ", "頭は遅らせて引っ張る"], prereqs: ["butterfly-kick"], leads: ["cheat-720", "cork"] },
  { id: "cheat-720", genre: "tricking", name_ja: "チート720", name_en: "Cheat 720", lv: 6, tags: ["kick", "spin"], desc_ja: "2回転の蹴り技。540の上位。", desc_en: "Two-rotation cheat kick.", tips_ja: ["プリセットの逆ひねりを深く", "蹴りは1回目で出す", "着地脚を引き続ける"], prereqs: ["540-kick"], leads: [] },
  { id: "cork", genre: "tricking", name_ja: "コーク", name_en: "Cork", lv: 7, tags: ["flip", "off-axis"], desc_ja: "斜め軸のオフアクシスフリップ。", desc_en: "Off-axis backward rotation flip.", tips_ja: ["セットを斜めに倒す", "腕は強くラップ", "視線で着地を探す"], prereqs: ["butterfly-twist", "back-tuck"], leads: ["raiz"] },
  { id: "raiz", genre: "tricking", name_ja: "ライズ", name_en: "Raiz", lv: 5, tags: ["flip", "no-hand"], desc_ja: "ノーハンドのサイドフリップ系。", desc_en: "No-handed side flip variant.", tips_ja: ["前足の踏切で斜め上へ", "腕を強く回す", "膝抱えで回転半径を縮める"], prereqs: ["aerial"], leads: [] },
  { id: "gainer", genre: "tricking", name_ja: "ゲイナー", name_en: "Gainer", lv: 5, tags: ["flip", "backward"], desc_ja: "前進しながら後方宙返り。", desc_en: "Backflip while moving forward.", tips_ja: ["片脚を強く前にスイング", "上体を反らさない", "回転軸は移動方向"], prereqs: ["back-tuck"], leads: [] },
  { id: "snapuswipe", genre: "tricking", name_ja: "スナップユースワイプ", name_en: "Snapuswipe", lv: 7, tags: ["combo", "front"], desc_ja: "ウェブスター後にバックフリップを連結。", desc_en: "Webster into back flip combination.", tips_ja: ["ウェブスターの着地で潰さない", "蹴り脚で前に押す", "上体は遅らせる"], prereqs: ["webster", "back-tuck"], leads: [] },

  // ─────────── PARKOUR (13) ───────────
  { id: "parkour-roll", genre: "parkour", name_ja: "受け身ロール", name_en: "Parkour Roll", lv: 1, tags: ["safety", "basic"], desc_ja: "肩から斜めに転がる衝撃吸収の基本。", desc_en: "Diagonal shoulder roll to absorb landing impact.", tips_ja: ["対角線で頭を入れる", "背中を丸める", "立ち上がりまで連続動作"], prereqs: [], leads: ["dive-roll"] },
  { id: "precision", genre: "parkour", name_ja: "プレシジョン", name_en: "Precision Jump", lv: 2, tags: ["jump", "balance"], desc_ja: "縁から縁へ正確に着地する基礎ジャンプ。", desc_en: "Standing jump to a precise landing point.", tips_ja: ["腕の振り上げで初速を作る", "母指球で着地", "膝で吸収"], prereqs: [], leads: ["cat-leap"] },
  { id: "cat-leap", genre: "parkour", name_ja: "キャットリープ", name_en: "Cat Leap", lv: 3, tags: ["jump", "climb"], desc_ja: "壁面に手と足で同時に着く跳躍。", desc_en: "Hands-and-feet wall catch jump.", tips_ja: ["手は鉄棒のように握る", "足は壁を蹴る位置に", "腰を引かない"], prereqs: ["precision"], leads: [] },
  { id: "kong-vault", genre: "parkour", name_ja: "コングボルト", name_en: "Kong Vault", lv: 4, tags: ["vault"], desc_ja: "両手をついて両脚を抱え込み飛び越える。", desc_en: "Diving vault with both hands and tucked legs.", tips_ja: ["手の着き位置を奥に", "腰を高く上げる", "押し放しで前進する"], prereqs: ["speed-vault"], leads: ["dive-kong"] },
  { id: "speed-vault", genre: "parkour", name_ja: "スピードボルト", name_en: "Speed Vault", lv: 2, tags: ["vault"], desc_ja: "片手だけついて横向きに飛び越える最速のボルト。", desc_en: "Single-hand sideways vault.", tips_ja: ["強い踏切脚を選ぶ", "手は軽く触れる程度", "肩を進行方向に向ける"], prereqs: [], leads: ["kong-vault", "lazy-vault"] },
  { id: "lazy-vault", genre: "parkour", name_ja: "レイジーボルト", name_en: "Lazy Vault", lv: 2, tags: ["vault"], desc_ja: "片手のスムーズな低エネルギーボルト。", desc_en: "Smooth low-energy single-hand vault.", tips_ja: ["脚を順に振り上げる", "視線は進行方向", "手は最後に押し離す"], prereqs: ["speed-vault"], leads: ["reverse-vault"] },
  { id: "reverse-vault", genre: "parkour", name_ja: "リバースボルト", name_en: "Reverse Vault", lv: 4, tags: ["vault", "spin"], desc_ja: "障害物上で360度回転しながら越える。", desc_en: "Vault while spinning 360° over the obstacle.", tips_ja: ["回転は上体から", "手で押し続ける", "着地は進行方向を向く"], prereqs: ["lazy-vault"], leads: ["palm-spin"] },
  { id: "wall-run", genre: "parkour", name_ja: "ウォールラン", name_en: "Wall Run", lv: 3, tags: ["wall"], desc_ja: "壁を駆け上がり頂点を掴む。", desc_en: "Run up a wall to grab the top.", tips_ja: ["最初の蹴りを高く", "母指球で押す", "視線を上に固定"], prereqs: [], leads: ["wall-flip", "tic-tac"] },
  { id: "tic-tac", genre: "parkour", name_ja: "ティックタック", name_en: "Tic Tac", lv: 3, tags: ["wall"], desc_ja: "壁を踏み台に方向転換するキック。", desc_en: "Wall push-off to change direction.", tips_ja: ["蹴り脚は壁に対し斜め", "上体を進行方向へ", "1〜2歩でリリース"], prereqs: ["wall-run"], leads: ["wall-flip"] },
  { id: "wall-flip", genre: "parkour", name_ja: "ウォールフリップ", name_en: "Wall Flip", lv: 6, tags: ["flip", "wall"], desc_ja: "壁を蹴ってバックフリップ。", desc_en: "Backflip off a wall.", tips_ja: ["壁蹴りで真上に押す", "頭を強く引く", "視線で着地を捉える"], prereqs: ["tic-tac", "back-tuck"], leads: [] },
  { id: "dive-roll", genre: "parkour", name_ja: "ダイブロール", name_en: "Dive Roll", lv: 3, tags: ["roll", "safety"], desc_ja: "前方に飛び込んで受け身ロールへ繋ぐ。", desc_en: "Dive forward into a parkour roll.", tips_ja: ["腕を伸ばし斜めに着く", "肩でラインを作る", "勢いを殺さない"], prereqs: ["parkour-roll"], leads: ["dive-kong"] },
  { id: "dive-kong", genre: "parkour", name_ja: "ダイブコング", name_en: "Dive Kong", lv: 5, tags: ["vault", "jump"], desc_ja: "ダイブして両手で押すコング。", desc_en: "Diving Kong vault with extended approach.", tips_ja: ["遠くから飛び込む", "腰を高く保つ", "押し離しで距離を稼ぐ"], prereqs: ["kong-vault", "dive-roll"], leads: [] },
  { id: "palm-spin", genre: "parkour", name_ja: "パームスピン", name_en: "Palm Spin", lv: 4, tags: ["vault", "spin"], desc_ja: "片手で支点を作り回転して越える。", desc_en: "Single-hand pivot spin over an obstacle.", tips_ja: ["支点の手の位置を奥に", "腰を上げる", "回転は遠心力で"], prereqs: ["reverse-vault"], leads: [] },

  // ─────────── GYMNASTICS (13) ───────────
  { id: "handstand", genre: "gym", name_ja: "倒立", name_en: "Handstand", lv: 3, tags: ["balance", "static"], desc_ja: "全ての逆さ系の土台。", desc_en: "Foundational inverted balance.", tips_ja: ["指で床を掴む", "肩を耳の横まで開く", "腰を真上に積む"], prereqs: [], leads: ["press-handstand", "planche"] },
  { id: "cartwheel", genre: "gym", name_ja: "側転", name_en: "Cartwheel", lv: 1, tags: ["basic", "rotation"], desc_ja: "横方向の回転。基礎中の基礎。", desc_en: "Sideways rotation on hands.", tips_ja: ["手は一直線", "脚は真上で開く", "リズムは1-2-3-4"], prereqs: [], leads: ["round-off", "aerial"] },
  { id: "back-handspring", genre: "gym", name_ja: "バック転", name_en: "Back Handspring", lv: 4, tags: ["flip", "backward"], desc_ja: "後方に手を着いて反転する基礎タンブリング。", desc_en: "Backward hand-spring with hand contact.", tips_ja: ["椅子に座る姿勢で開始", "腕は耳の横を通す", "脚は鞭のように振る"], prereqs: ["round-off"], leads: ["back-tuck", "back-layout"] },
  { id: "front-handspring", genre: "gym", name_ja: "前方転回", name_en: "Front Handspring", lv: 3, tags: ["flip", "frontward"], desc_ja: "前方への手転回。", desc_en: "Forward hand-spring.", tips_ja: ["押し離しを強く", "腰を高く保つ", "着地は腕を上に"], prereqs: ["handstand"], leads: ["front-tuck"] },
  { id: "front-tuck", genre: "gym", name_ja: "前宙", name_en: "Front Tuck", lv: 4, tags: ["flip", "frontward"], desc_ja: "前方宙返り。両足踏切で回る。", desc_en: "Forward somersault.", tips_ja: ["真上に跳ぶ", "膝を強く抱える", "視線で着地を取る"], prereqs: ["front-handspring"], leads: [] },
  { id: "back-layout", genre: "gym", name_ja: "バックレイアウト", name_en: "Back Layout", lv: 6, tags: ["flip", "extended"], desc_ja: "伸身バック宙。タック→レイアウトへ。", desc_en: "Layout (straight body) back somersault.", tips_ja: ["体を一直線に保つ", "腕は早く下ろす", "肩で回転を引く"], prereqs: ["back-tuck"], leads: ["back-full", "double-back"] },
  { id: "planche", genre: "gym", name_ja: "プランシェ", name_en: "Planche", lv: 8, tags: ["strength", "static"], desc_ja: "床と平行に体を支える静止技。", desc_en: "Body held parallel to floor on arms.", tips_ja: ["肩を前に大きく出す", "胸を地面に近づける", "Tuck → Straddle → Fullと段階的に"], prereqs: ["handstand"], leads: [] },
  { id: "front-lever", genre: "gym", name_ja: "フロントレバー", name_en: "Front Lever", lv: 7, tags: ["strength", "bar"], desc_ja: "鉄棒で水平に体を保つ。", desc_en: "Horizontal hold on a bar, face up.", tips_ja: ["背中で引く", "骨盤を立てる", "Tuckから始める"], prereqs: [], leads: ["iron-cross"] },
  { id: "iron-cross", genre: "gym", name_ja: "鉄十字", name_en: "Iron Cross", lv: 9, tags: ["strength", "ring"], desc_ja: "吊り輪で十字に静止する究極のストレングス。", desc_en: "Iron Cross hold on rings.", tips_ja: ["肩関節の前傾を作る", "リング外旋を保つ", "段階的にバンド補助で"], prereqs: ["front-lever"], leads: [] },
  { id: "round-off-bh", genre: "gym", name_ja: "ロンダート→バック転", name_en: "Round-off Back Handspring", lv: 5, tags: ["combo", "tumbling"], desc_ja: "全タンブリングの基幹パワーパス。", desc_en: "Fundamental tumbling power pass.", tips_ja: ["ロンダートで加速", "着地で潰さない", "腕を強く後ろへ振る"], prereqs: ["round-off", "back-handspring"], leads: ["back-tuck"] },
  { id: "double-back", genre: "gym", name_ja: "ダブルバック", name_en: "Double Back", lv: 9, tags: ["flip", "double"], desc_ja: "2回連続の後方宙返り。", desc_en: "Double back somersault.", tips_ja: ["高さを最優先", "1回目は強くタック", "2回目で開く"], prereqs: ["back-layout"], leads: [] },
  { id: "fouette", genre: "gym", name_ja: "フェッテ", name_en: "Fouetté", lv: 4, tags: ["spin", "balance"], desc_ja: "片足ピボットで回るアクシス回転。", desc_en: "Single-leg whip turn.", tips_ja: ["スポットを取る", "脚を素早く戻す", "腕で勢いをまとめる"], prereqs: [], leads: [] },
  { id: "press-handstand", genre: "gym", name_ja: "プレス倒立", name_en: "Press Handstand", lv: 7, tags: ["strength", "balance"], desc_ja: "脚を上げてゆっくり倒立に入る。", desc_en: "Slow controlled press into a handstand.", tips_ja: ["肩前傾を強く", "脚は最後に上げる", "ストラドルから練習"], prereqs: ["handstand"], leads: ["planche"] },

  // ─────────── BREAKDANCE (13) ───────────
  { id: "toprock", genre: "break", name_ja: "トップロック", name_en: "Top Rock", lv: 1, tags: ["basic", "standing"], desc_ja: "立ちで踊る基礎リズム。", desc_en: "Standing rhythm patterns.", tips_ja: ["重心は中央", "肩でビートを取る", "クロスステップから"], prereqs: [], leads: ["6-step"] },
  { id: "6-step", genre: "break", name_ja: "6ステップ", name_en: "6-Step", lv: 2, tags: ["footwork", "basic"], desc_ja: "床上で円を描くフットワーク基礎。", desc_en: "Foundational floor footwork pattern.", tips_ja: ["手は肩の真下", "腰を低く保つ", "リズムキープが最優先"], prereqs: ["toprock"], leads: ["cc", "swipe"] },
  { id: "cc", genre: "break", name_ja: "CC", name_en: "CC", lv: 3, tags: ["footwork"], desc_ja: "片脚を回しながら反対脚を抜くフットワーク。", desc_en: "Footwork pattern with leg sweeps.", tips_ja: ["片手のみで支える", "脚は床スレスレ", "目線は内側"], prereqs: ["6-step"], leads: ["windmill"] },
  { id: "swipe", genre: "break", name_ja: "スワイプ", name_en: "Swipe", lv: 4, tags: ["power"], desc_ja: "両手両足で床を擦りながら回るパワームーブ。", desc_en: "Power move sweeping hands and feet.", tips_ja: ["最初の手で床を強く打つ", "腰を低く投げる", "回転は腰主導"], prereqs: ["6-step"], leads: ["windmill", "halo"] },
  { id: "windmill", genre: "break", name_ja: "ウインドミル", name_en: "Windmill", lv: 5, tags: ["power", "spin"], desc_ja: "肩と背中で連続回転するパワームーブの王道。", desc_en: "Classic power move spinning on shoulders/back.", tips_ja: ["脚を大きく開く", "肘でブロックを作る", "胸を抜くタイミング"], prereqs: ["swipe"], leads: ["babymill", "halo", "flare"] },
  { id: "babymill", genre: "break", name_ja: "ベビーミル", name_en: "Baby Windmill", lv: 5, tags: ["power"], desc_ja: "脚を折りたたんだコンパクトなウインドミル。", desc_en: "Tucked-leg windmill variation.", tips_ja: ["脚をクロス気味に保つ", "回転半径を小さく", "肘ブロックは深く"], prereqs: ["windmill"], leads: [] },
  { id: "halo", genre: "break", name_ja: "ヘイロー", name_en: "Halo", lv: 6, tags: ["power", "head"], desc_ja: "頭を支点に円を描き続けるパワームーブ。", desc_en: "Continuous head-on-floor circular power move.", tips_ja: ["額の正面を使う", "首は固める", "腰で円を描く"], prereqs: ["windmill"], leads: ["headspin"] },
  { id: "headspin", genre: "break", name_ja: "ヘッドスピン", name_en: "Headspin", lv: 7, tags: ["power", "head", "spin"], desc_ja: "頭頂で回転し続けるアイコニックな技。", desc_en: "Iconic spin on the crown of the head.", tips_ja: ["首の真上で支える", "脚で回転を維持", "手のタップでブースト"], prereqs: ["halo"], leads: [] },
  { id: "flare", genre: "break", name_ja: "フレア", name_en: "Flare", lv: 7, tags: ["power", "spin"], desc_ja: "脚を開いたまま体を浮かせて回る。", desc_en: "Open-leg airborne circular move.", tips_ja: ["腕の入れ替えを早く", "脚は床と平行", "腰を高く保つ"], prereqs: ["windmill"], leads: ["air-flare"] },
  { id: "air-flare", genre: "break", name_ja: "エアフレア", name_en: "Air Flare", lv: 9, tags: ["power", "spin", "elite"], desc_ja: "床に脚を着けず空中でフレアを続ける。", desc_en: "Airborne flare with no leg contact.", tips_ja: ["強い跳躍で開始", "斜め軸を保つ", "腕の押し替えで継続"], prereqs: ["flare"], leads: [] },
  { id: "baby-freeze", genre: "break", name_ja: "ベビーフリーズ", name_en: "Baby Freeze", lv: 2, tags: ["freeze", "basic"], desc_ja: "肘を腹に当てて静止するフリーズ基礎。", desc_en: "Basic freeze on elbows and head.", tips_ja: ["肘は骨盤に刺す", "頭でバランスを取る", "脚はクロスで固定"], prereqs: [], leads: ["chair-freeze", "turtle"] },
  { id: "chair-freeze", genre: "break", name_ja: "チェアフリーズ", name_en: "Chair Freeze", lv: 3, tags: ["freeze"], desc_ja: "肘で体を支え横向きに静止。", desc_en: "Sideways freeze on a single elbow.", tips_ja: ["肘を腰骨に刺す", "脚で形を作る", "視線で全身を整える"], prereqs: ["baby-freeze"], leads: [] },
  { id: "turtle", genre: "break", name_ja: "タートル", name_en: "Turtle", lv: 4, tags: ["freeze", "spin"], desc_ja: "両肘で支え円を描くスピン系フリーズ。", desc_en: "Two-elbow rotating freeze.", tips_ja: ["肘は骨盤の左右", "重心を手の間に", "押し替えで回す"], prereqs: ["baby-freeze"], leads: [] },

  // ─────────── SKI (13) ───────────
  { id: "ski-180", genre: "ski", name_ja: "ski 180", name_en: "Ski 180", lv: 2, tags: ["spin", "basic"], desc_ja: "半回転スピン。スイッチ着地が必要。", desc_en: "Half-rotation in the air, switch landing.", tips_ja: ["肩でプリセット", "視線を90度残す", "着地に向け開く"], prereqs: [], leads: ["ski-360"] },
  { id: "ski-360", genre: "ski", name_ja: "ski 360", name_en: "Ski 360", lv: 3, tags: ["spin"], desc_ja: "1回転スピン。フリースキー基礎。", desc_en: "Full rotation in the air.", tips_ja: ["上体でプリセット", "スポットで着地を探す", "板はフラットに保つ"], prereqs: ["ski-180"], leads: ["ski-540", "ski-cork-720"] },
  { id: "ski-540", genre: "ski", name_ja: "ski 540", name_en: "Ski 540", lv: 4, tags: ["spin"], desc_ja: "1回転半スピン。", desc_en: "One-and-a-half rotation spin.", tips_ja: ["プリセットを深く", "回転途中で姿勢を絞る", "視線で着地"], prereqs: ["ski-360"], leads: ["ski-720"] },
  { id: "ski-720", genre: "ski", name_ja: "ski 720", name_en: "Ski 720", lv: 5, tags: ["spin"], desc_ja: "2回転スピン。", desc_en: "Two-rotation aerial spin.", tips_ja: ["離陸時の角度が鍵", "腕で回転を絞る", "1回転目で着地を予測"], prereqs: ["ski-540"], leads: ["ski-cork-720", "ski-flatspin"] },
  { id: "ski-cork-720", genre: "ski", name_ja: "コーク720", name_en: "Cork 720", lv: 7, tags: ["spin", "flip", "off-axis"], desc_ja: "斜め軸で2回転するオフアクシス。", desc_en: "Off-axis double rotation flip.", tips_ja: ["離陸で軸を傾ける", "肩で回転を導く", "視線で空を捉える"], prereqs: ["ski-720"], leads: ["ski-double-cork"] },
  { id: "ski-misty", genre: "ski", name_ja: "ミスティ", name_en: "Misty Flip", lv: 6, tags: ["flip", "off-axis"], desc_ja: "斜め前方軸のフリップ。", desc_en: "Off-axis forward flip rotation.", tips_ja: ["前方への踏切", "斜め軸を維持", "膝で着地吸収"], prereqs: ["ski-360"], leads: [] },
  { id: "ski-rodeo", genre: "ski", name_ja: "ロデオ", name_en: "Rodeo", lv: 6, tags: ["flip", "off-axis"], desc_ja: "後方斜め軸のフリップ。", desc_en: "Off-axis backward flip rotation.", tips_ja: ["後ろに倒すセット", "肩でリード", "回転後に視線で着地"], prereqs: ["ski-360"], leads: [] },
  { id: "ski-backflip", genre: "ski", name_ja: "ski バックフリップ", name_en: "Ski Backflip", lv: 5, tags: ["flip"], desc_ja: "後方宙返り。", desc_en: "Straight backflip on skis.", tips_ja: ["真上に強く跳ぶ", "視線は後ろの空", "回転は速やかに"], prereqs: [], leads: ["ski-cork-720"] },
  { id: "ski-daffy", genre: "ski", name_ja: "ダフィー", name_en: "Daffy", lv: 2, tags: ["grab", "stylish"], desc_ja: "片脚前・片脚後ろの空中ポーズ。", desc_en: "Front-back split mid-air pose.", tips_ja: ["前脚を真っ直ぐ伸ばす", "後ろ脚は曲げる", "空中で1拍ホールド"], prereqs: [], leads: [] },
  { id: "ski-mute", genre: "ski", name_ja: "ミュート", name_en: "Mute Grab", lv: 3, tags: ["grab"], desc_ja: "反対の手で板の前方外側を掴む。", desc_en: "Cross-grab of front-outside ski.", tips_ja: ["膝を引き上げる", "腕は短くまとめる", "視線は前"], prereqs: [], leads: ["ski-safety"] },
  { id: "ski-safety", genre: "ski", name_ja: "セーフティ", name_en: "Safety Grab", lv: 3, tags: ["grab"], desc_ja: "同じ側の手で板の内側を掴む。", desc_en: "Same-side inside grab.", tips_ja: ["脚を高く抱える", "腰を曲げない", "ホールドを長く"], prereqs: ["ski-mute"], leads: [] },
  { id: "ski-flatspin", genre: "ski", name_ja: "フラットスピン", name_en: "Flat Spin", lv: 6, tags: ["spin", "off-axis"], desc_ja: "水平軸寄りの斜め回転。", desc_en: "Near-horizontal axis spin.", tips_ja: ["体を地面と平行に倒す", "回転は腰主導", "視線で軸を保つ"], prereqs: ["ski-540"], leads: [] },
  { id: "ski-double-cork", genre: "ski", name_ja: "ダブルコーク", name_en: "Double Cork", lv: 9, tags: ["flip", "double", "elite"], desc_ja: "斜め軸で2回フリップ。コンペ必須技。", desc_en: "Two off-axis flips — competition staple.", tips_ja: ["離陸角度を深く", "1回目で速度を作る", "視線で2回目の着地を取る"], prereqs: ["ski-cork-720"], leads: [] },

  // ─────────── SNOWBOARD (14) ───────────
  { id: "sb-ollie", genre: "snow", name_ja: "オーリー", name_en: "Ollie", lv: 1, tags: ["basic", "air"], desc_ja: "テールを弾いて板ごと跳ぶ基礎。", desc_en: "Pop trick using the tail.", tips_ja: ["後ろ脚で強く弾く", "前脚を引き上げる", "板を水平に保つ"], prereqs: [], leads: ["sb-180", "sb-method"] },
  { id: "sb-nollie", genre: "snow", name_ja: "ノーリー", name_en: "Nollie", lv: 2, tags: ["basic", "air"], desc_ja: "ノーズで弾くオーリーの逆。", desc_en: "Nose-pop ollie variant.", tips_ja: ["前脚で弾く", "後ろ脚を引き上げる", "重心は中央寄り"], prereqs: ["sb-ollie"], leads: [] },
  { id: "sb-180", genre: "snow", name_ja: "sb 180", name_en: "SB 180", lv: 2, tags: ["spin"], desc_ja: "半回転スピン。スイッチ着地。", desc_en: "Half rotation, switch landing.", tips_ja: ["肩でプリセット", "視線で90度残す", "着地でエッジ切替"], prereqs: ["sb-ollie"], leads: ["sb-360"] },
  { id: "sb-360", genre: "snow", name_ja: "sb 360", name_en: "SB 360", lv: 3, tags: ["spin"], desc_ja: "1回転スピン。", desc_en: "Full air rotation.", tips_ja: ["上体でプリセット", "腕で絞る", "視線で着地を取る"], prereqs: ["sb-180"], leads: ["sb-540"] },
  { id: "sb-540", genre: "snow", name_ja: "sb 540", name_en: "SB 540", lv: 4, tags: ["spin"], desc_ja: "1回転半スピン。", desc_en: "One-and-a-half air rotation.", tips_ja: ["離陸を高く", "プリセットを深く", "回転半径を絞る"], prereqs: ["sb-360"], leads: ["sb-720"] },
  { id: "sb-720", genre: "snow", name_ja: "sb 720", name_en: "SB 720", lv: 6, tags: ["spin"], desc_ja: "2回転スピン。", desc_en: "Two-rotation aerial.", tips_ja: ["離陸角度を深く", "腕で1回目を作る", "2回目で開く"], prereqs: ["sb-540"], leads: ["sb-mctwist"] },
  { id: "sb-method", genre: "snow", name_ja: "メソッド", name_en: "Method Grab", lv: 4, tags: ["grab", "stylish"], desc_ja: "板を背中側に引き上げるスタイル技の王道。", desc_en: "Stylish backside grab — boarding's signature.", tips_ja: ["背中側に引き上げる", "腕を伸ばしてリード", "ホールドを長く"], prereqs: ["sb-ollie"], leads: [] },
  { id: "sb-indy", genre: "snow", name_ja: "インディ", name_en: "Indy Grab", lv: 3, tags: ["grab"], desc_ja: "後ろ手で板の前足側を掴む。", desc_en: "Trailing hand on the front-toe edge.", tips_ja: ["脚を抱え込む", "肩は進行方向", "ホールドを長く"], prereqs: ["sb-ollie"], leads: ["sb-cork"] },
  { id: "sb-mute", genre: "snow", name_ja: "ミュート", name_en: "Mute Grab", lv: 3, tags: ["grab"], desc_ja: "前手で前足側を掴む。", desc_en: "Front hand on the front-toe edge.", tips_ja: ["膝を引き上げる", "腕を短くまとめる", "板を真下に"], prereqs: ["sb-ollie"], leads: [] },
  { id: "sb-stalefish", genre: "snow", name_ja: "ステイルフィッシュ", name_en: "Stalefish", lv: 4, tags: ["grab"], desc_ja: "後ろ手で背中側のエッジを掴む。", desc_en: "Trailing hand on heel edge between bindings.", tips_ja: ["体を後ろにひねる", "脚を伸ばし気味に", "ホールドで魅せる"], prereqs: ["sb-indy"], leads: [] },
  { id: "sb-backflip", genre: "snow", name_ja: "sb バックフリップ", name_en: "SB Backflip", lv: 5, tags: ["flip"], desc_ja: "後方宙返り。", desc_en: "Straight backflip on board.", tips_ja: ["真上に強く跳ぶ", "頭を後ろに引く", "膝で着地吸収"], prereqs: [], leads: ["sb-cork"] },
  { id: "sb-cork", genre: "snow", name_ja: "コーク", name_en: "SB Cork", lv: 6, tags: ["flip", "off-axis"], desc_ja: "斜め軸のフリップ系スピン。", desc_en: "Off-axis backward rotation.", tips_ja: ["離陸で軸を倒す", "肩で回転を導く", "視線で着地を捉える"], prereqs: ["sb-360", "sb-backflip"], leads: ["sb-double-cork"] },
  { id: "sb-mctwist", genre: "snow", name_ja: "マクツイスト", name_en: "McTwist", lv: 7, tags: ["flip", "spin"], desc_ja: "540のひねりにバックフリップを足した複合技。", desc_en: "Inverted 540 — flip combined with rotation.", tips_ja: ["バックフリップでセット", "ひねりは頂点で", "視線で着地"], prereqs: ["sb-540", "sb-backflip"], leads: [] },
  { id: "sb-double-cork", genre: "snow", name_ja: "ダブルコーク", name_en: "Double Cork", lv: 9, tags: ["flip", "double", "elite"], desc_ja: "2回のオフアクシスフリップ。コンペ必須。", desc_en: "Two off-axis flips — pro competition staple.", tips_ja: ["強い離陸", "1回目で勢いを作る", "視線で2回目の着地"], prereqs: ["sb-cork"], leads: [] },

  // ─────────── TRICKING 拡張 (14) ───────────
  { id: "cheat-360", genre: "tricking", name_ja: "チート360", name_en: "Cheat 360", lv: 2, tags: ["kick", "spin"], desc_ja: "踏み切り前に上体をひねって反動を作る基礎スピンキック。", desc_en: "Basic spinning kick using a pre-rotation cheat.", tips_ja: ["上体のプリセットを深く", "蹴り脚を真っ直ぐ伸ばす", "着地で軸を保つ"], prereqs: [], leads: ["540-kick"] },
  { id: "pop-360", genre: "tricking", name_ja: "ポップ360", name_en: "Pop 360", lv: 3, tags: ["spin", "basic"], desc_ja: "両足踏み切りで真上に跳び1回転するスピン。", desc_en: "Two-foot pop with a full 360 spin.", tips_ja: ["真上への跳躍を意識", "腕で回転を巻き込む", "頭は最後まで残す"], prereqs: [], leads: ["cork"] },
  { id: "flashkick", genre: "tricking", name_ja: "フラッシュキック", name_en: "Flash Kick", lv: 4, tags: ["kick", "backward"], desc_ja: "後方に反りながら脚を振り上げるバック系キック。", desc_en: "Backward kick with an arched, whipping leg.", tips_ja: ["振り上げ脚を鞭のように", "上体の反りで高さを出す", "視線で着地を探す"], prereqs: ["back-tuck"], leads: ["flash-360"] },
  { id: "flash-360", genre: "tricking", name_ja: "フラッシュ360", name_en: "Flash 360", lv: 6, tags: ["kick", "twist"], desc_ja: "フラッシュキックに360度ひねりを加えた複合技。", desc_en: "Flash kick with an added 360 twist.", tips_ja: ["ひねりは頂点で開始", "腕を強くラップ", "蹴りとひねりを分離"], prereqs: ["flashkick"], leads: [] },
  { id: "hook-kick", genre: "tricking", name_ja: "フックキック", name_en: "Hook Kick", lv: 5, tags: ["kick"], desc_ja: "空中でフックを描く軌道の蹴り技。", desc_en: "Aerial kick tracing a hooking arc.", tips_ja: ["軸足の引き上げを速く", "蹴り脚で弧を描く", "上体を残して回す"], prereqs: ["540-kick"], leads: ["hyperhook"] },
  { id: "hyperhook", genre: "tricking", name_ja: "ハイパーフック", name_en: "Hyperhook", lv: 6, tags: ["kick", "off-axis"], desc_ja: "斜め軸で繰り出すフックキックの発展技。", desc_en: "Off-axis variation of the hook kick.", tips_ja: ["軸を斜めに倒す", "蹴り脚を長く使う", "肩で回転を導く"], prereqs: ["hook-kick"], leads: [] },
  { id: "swing", genre: "tricking", name_ja: "スイング", name_en: "Swing", lv: 2, tags: ["transition", "basic"], desc_ja: "技と技をつなぐ基礎的なスイング動作。", desc_en: "Fundamental momentum-carrying transition.", tips_ja: ["腕で勢いを作る", "腰の回転に乗せる", "次の技へ流れを止めない"], prereqs: [], leads: ["swingthrough"] },
  { id: "swingthrough", genre: "tricking", name_ja: "スイングスルー", name_en: "Swing Through", lv: 3, tags: ["transition", "combo"], desc_ja: "スイングから次技へ滑らかに連結する繋ぎ技。", desc_en: "Swing transition flowing into the next trick.", tips_ja: ["着地で潰さない", "勢いを次へ渡す", "視線を進行方向に"], prereqs: ["swing"], leads: [] },
  { id: "vanish", genre: "tricking", name_ja: "ヴァニッシュ", name_en: "Vanish", lv: 4, tags: ["transition"], desc_ja: "脚を入れ替えながら向きを変える繋ぎのフットワーク。", desc_en: "Footwork transition that switches stance mid-flow.", tips_ja: ["脚の入れ替えを素早く", "上体の向きを先行", "リズムを保つ"], prereqs: ["swing"], leads: [] },
  { id: "double-leg", genre: "tricking", name_ja: "ダブルレッグ", name_en: "Double Leg", lv: 4, tags: ["kick", "spin"], desc_ja: "両脚を時間差で振り上げる横回転キック。", desc_en: "Horizontal spin kick whipping both legs.", tips_ja: ["上半身を倒し込む", "両脚を時間差で", "腰主導で回す"], prereqs: ["butterfly-kick"], leads: [] },
  { id: "touchdown-raiz", genre: "tricking", name_ja: "タッチダウンライズ", name_en: "Touchdown Raiz", lv: 6, tags: ["flip", "no-hand"], desc_ja: "片手を軽く触れて軸を作るライズの派生技。", desc_en: "Raiz variant touching a hand down for the axis.", tips_ja: ["手は支点として軽く", "斜め上へ蹴り出す", "膝抱えで回転を締める"], prereqs: ["raiz"], leads: [] },
  { id: "cork-double", genre: "tricking", name_ja: "ダブルコーク", name_en: "Double Cork", lv: 9, tags: ["flip", "double", "elite"], desc_ja: "斜め軸で2回転するコークの上位技。", desc_en: "Two off-axis rotations — double cork.", tips_ja: ["強い踏み切りで高さを確保", "1回目で速度を作る", "視線で2回目の着地を取る"], prereqs: ["cork"], leads: [] },
  { id: "boxcutter", genre: "tricking", name_ja: "ボックスカッター", name_en: "Boxcutter", lv: 8, tags: ["flip", "kick", "off-axis"], desc_ja: "コークの回転中にフックキックを抜く複合技。", desc_en: "Cork combined with a hook kick on the way out.", tips_ja: ["コークのセットを深く", "頂点でキックを抜く", "蹴りで着地方向を定める"], prereqs: ["cork"], leads: [] },
  { id: "gainer-switch", genre: "tricking", name_ja: "ゲイナースイッチ", name_en: "Gainer Switch", lv: 7, tags: ["flip", "backward"], desc_ja: "ゲイナー中に踏み切り脚を入れ替える発展技。", desc_en: "Gainer with a mid-air leg switch.", tips_ja: ["スイング脚を強く前へ", "空中で脚を入れ替える", "回転軸を移動方向に保つ"], prereqs: ["gainer"], leads: [] },

  // ─────────── PARKOUR 拡張 (14) ───────────
  { id: "drop", genre: "parkour", name_ja: "ドロップ", name_en: "Drop", lv: 1, tags: ["safety", "basic"], desc_ja: "高所から飛び降り衝撃を吸収する基本動作。", desc_en: "Controlled landing from a height.", tips_ja: ["母指球から着地", "膝と股関節で吸収", "上体を前傾させすぎない"], prereqs: [], leads: ["parkour-roll"] },
  { id: "rail-balance", genre: "parkour", name_ja: "レールバランス", name_en: "Rail Balance", lv: 1, tags: ["balance", "basic"], desc_ja: "細い縁の上を歩く基礎バランス。", desc_en: "Walking balance on a narrow rail.", tips_ja: ["視線は遠くへ", "腕で微調整", "母指球で縁を掴む"], prereqs: [], leads: ["cat-balance"] },
  { id: "cat-balance", genre: "parkour", name_ja: "キャットバランス", name_en: "Cat Balance", lv: 3, tags: ["balance", "climb"], desc_ja: "手足でレール上を四つ這いで進むバランス。", desc_en: "Quadrupedal balance moving along a rail.", tips_ja: ["重心を低く保つ", "手と足を交互に", "視線は進行方向"], prereqs: ["rail-balance"], leads: [] },
  { id: "stride", genre: "parkour", name_ja: "ストライド", name_en: "Stride", lv: 2, tags: ["jump", "basic"], desc_ja: "片足踏み切り・片足着地で間を跨ぐジャンプ。", desc_en: "One-foot takeoff, one-foot landing gap jump.", tips_ja: ["走りの勢いを使う", "着地脚で吸収", "視線を着地点へ"], prereqs: ["precision"], leads: ["running-precision"] },
  { id: "running-precision", genre: "parkour", name_ja: "ランニングプレシジョン", name_en: "Running Precision", lv: 3, tags: ["jump", "balance"], desc_ja: "助走から縁へ正確に着地するジャンプ。", desc_en: "Precision landing performed from a run-up.", tips_ja: ["最後の一歩で踏み切る", "空中で姿勢を整える", "母指球で着地"], prereqs: ["stride", "precision"], leads: [] },
  { id: "dash-vault", genre: "parkour", name_ja: "ダッシュボルト", name_en: "Dash Vault", lv: 3, tags: ["vault"], desc_ja: "先に脚を抜き後から手をつくボルト。", desc_en: "Vault leading with the feet, hands last.", tips_ja: ["脚を先に前へ送る", "手で後方を押す", "前進の勢いを保つ"], prereqs: ["speed-vault"], leads: ["kash-vault"] },
  { id: "thief-vault", genre: "parkour", name_ja: "シーフボルト", name_en: "Thief Vault", lv: 3, tags: ["vault"], desc_ja: "横向きにステップを踏んで越える素早いボルト。", desc_en: "Quick sideways step vault.", tips_ja: ["手は短く触れる", "脚を順に振り抜く", "肩を進行方向へ"], prereqs: ["speed-vault"], leads: [] },
  { id: "kash-vault", genre: "parkour", name_ja: "カッシュボルト", name_en: "Kash Vault", lv: 5, tags: ["vault", "combo"], desc_ja: "コングで入りダッシュで抜ける複合ボルト。", desc_en: "Kong entry transitioning into a dash exit.", tips_ja: ["コングで腰を高く", "途中で脚を前へ送る", "手で押し切る"], prereqs: ["kong-vault", "dash-vault"], leads: [] },
  { id: "double-kong", genre: "parkour", name_ja: "ダブルコング", name_en: "Double Kong", lv: 6, tags: ["vault"], desc_ja: "長い障害物を2回手をついて越えるコング。", desc_en: "Kong over a long obstacle with two hand pushes.", tips_ja: ["遠くから飛び込む", "1回目で距離を稼ぐ", "2回目で押し切る"], prereqs: ["kong-vault"], leads: [] },
  { id: "turn-vault", genre: "parkour", name_ja: "ターンボルト", name_en: "Turn Vault", lv: 2, tags: ["vault", "climb"], desc_ja: "縁を越えながら180度回転してぶら下がる動作。", desc_en: "Vault with a 180 turn into a hang.", tips_ja: ["手の持ち替えを早く", "腰から回す", "ぶら下がりで衝撃吸収"], prereqs: [], leads: [] },
  { id: "underbar", genre: "parkour", name_ja: "アンダーバー", name_en: "Underbar", lv: 3, tags: ["jump"], desc_ja: "隙間に脚から飛び込んで通り抜ける動作。", desc_en: "Diving feet-first through a gap.", tips_ja: ["脚を先に通す", "バーを引いて加速", "通過後すぐ着地姿勢"], prereqs: [], leads: [] },
  { id: "wall-spin", genre: "parkour", name_ja: "ウォールスピン", name_en: "Wall Spin", lv: 6, tags: ["wall", "spin"], desc_ja: "壁に手をついて体を回転させる技。", desc_en: "Spinning the body off a wall on the hands.", tips_ja: ["手の位置を高く", "腰で回転を作る", "視線で着地を探す"], prereqs: ["wall-run"], leads: [] },
  { id: "lache", genre: "parkour", name_ja: "ラシェ", name_en: "Laché", lv: 4, tags: ["jump", "bar"], desc_ja: "バーを掴んで振り、離して次へ跳ぶ動作。", desc_en: "Swinging off a bar and releasing to a target.", tips_ja: ["振りの頂点で離す", "視線を着地点へ", "肩で衝撃を逃がす"], prereqs: ["cat-leap"], leads: [] },
  { id: "climb-up", genre: "parkour", name_ja: "クライムアップ", name_en: "Climb Up", lv: 3, tags: ["climb", "wall"], desc_ja: "壁の縁を掴んだ状態から上に登り切る動作。", desc_en: "Pulling up over the top edge of a wall.", tips_ja: ["足で壁を押す", "引きと押しを連続で", "肘を素早く返す"], prereqs: ["cat-leap"], leads: [] },

  // ─────────── GYMNASTICS 拡張 (13) ───────────
  { id: "forward-roll", genre: "gym", name_ja: "前転", name_en: "Forward Roll", lv: 1, tags: ["basic", "rotation"], desc_ja: "前方へ丸まって転がる基礎技。", desc_en: "Basic forward roll.", tips_ja: ["顎を引く", "背中を丸める", "勢いで立ち上がる"], prereqs: [], leads: ["front-handspring"] },
  { id: "backward-roll", genre: "gym", name_ja: "後転", name_en: "Backward Roll", lv: 1, tags: ["basic", "rotation"], desc_ja: "後方へ丸まって転がる基礎技。", desc_en: "Basic backward roll.", tips_ja: ["手を耳の横に構える", "背中を丸める", "手で床を押す"], prereqs: [], leads: ["back-handspring"] },
  { id: "bridge", genre: "gym", name_ja: "ブリッジ", name_en: "Bridge", lv: 2, tags: ["flexibility", "static"], desc_ja: "背中を反らせて支えるブリッジ姿勢。", desc_en: "Back bridge hold.", tips_ja: ["肩の柔軟性を使う", "手足で均等に支える", "胸を開く"], prereqs: [], leads: ["walkover-back"] },
  { id: "walkover-front", genre: "gym", name_ja: "フロントウォークオーバー", name_en: "Front Walkover", lv: 3, tags: ["flip", "frontward"], desc_ja: "倒立を経由して前方へ反り返る連続技。", desc_en: "Front walkover through a handstand.", tips_ja: ["倒立で一度静止", "脚を順に下ろす", "胸を反らせて立つ"], prereqs: ["bridge", "handstand"], leads: ["front-handspring"] },
  { id: "walkover-back", genre: "gym", name_ja: "バックウォークオーバー", name_en: "Back Walkover", lv: 3, tags: ["flip", "backward"], desc_ja: "ブリッジから後方へ反り返る連続技。", desc_en: "Back walkover from a bridge.", tips_ja: ["脚を真上へ振り上げる", "肩を開く", "手で床を押し続ける"], prereqs: ["bridge"], leads: ["back-handspring"] },
  { id: "l-sit", genre: "gym", name_ja: "L字支持", name_en: "L-Sit", lv: 3, tags: ["strength", "static"], desc_ja: "両手で体を支え脚をL字に保つ静止技。", desc_en: "L-shaped support hold on the hands.", tips_ja: ["肩を下げる", "脚を水平に伸ばす", "腹で持ち上げる"], prereqs: [], leads: ["v-sit", "press-handstand"] },
  { id: "v-sit", genre: "gym", name_ja: "V字支持", name_en: "V-Sit", lv: 6, tags: ["strength", "static"], desc_ja: "脚を高く上げV字に保つ高難度の静止技。", desc_en: "V-shaped support hold with raised legs.", tips_ja: ["骨盤を立てる", "脚を顔に近づける", "肩を強く押し下げる"], prereqs: ["l-sit"], leads: [] },
  { id: "front-full", genre: "gym", name_ja: "前宙ひねり", name_en: "Front Full", lv: 6, tags: ["flip", "twist"], desc_ja: "前方宙返り中に1回ひねりを加える技。", desc_en: "Front somersault with a full twist.", tips_ja: ["真上に跳ぶ", "ひねりは早めに開始", "視線で着地を取る"], prereqs: ["front-tuck"], leads: [] },
  { id: "arabian", genre: "gym", name_ja: "アラビアン", name_en: "Arabian", lv: 7, tags: ["flip", "twist"], desc_ja: "半ひねりから前方宙返りへ移行する複合技。", desc_en: "Half twist into a front somersault.", tips_ja: ["バックの入りから半ひねり", "前方視野に切り替える", "膝を強く抱える"], prereqs: ["back-layout"], leads: [] },
  { id: "whip-back", genre: "gym", name_ja: "ウィップバック", name_en: "Whip Back", lv: 5, tags: ["flip", "backward", "tumbling"], desc_ja: "手をつかず鞭のように加速する後方連続技。", desc_en: "No-hand whipping back connection.", tips_ja: ["脚を鞭のように振る", "加速を殺さない", "次の技へ低く繋ぐ"], prereqs: ["back-handspring"], leads: ["back-tuck"] },
  { id: "double-front", genre: "gym", name_ja: "ダブルフロント", name_en: "Double Front", lv: 9, tags: ["flip", "double"], desc_ja: "2回連続の前方宙返り。", desc_en: "Double front somersault.", tips_ja: ["高さを最優先", "強く深くタック", "2回目で視線を着地へ"], prereqs: ["front-tuck"], leads: [] },
  { id: "full-in", genre: "gym", name_ja: "フルイン", name_en: "Full-In", lv: 9, tags: ["flip", "double", "twist", "elite"], desc_ja: "ダブルバックの1回目にひねりを入れる究極技。", desc_en: "Double back with a full twist in the first salto.", tips_ja: ["1回目でひねり切る", "高さを確保", "2回目はタックで締める"], prereqs: ["double-back"], leads: [] },
  { id: "straddle-planche", genre: "gym", name_ja: "ストラドルプランシェ", name_en: "Straddle Planche", lv: 7, tags: ["strength", "static"], desc_ja: "脚を開いて床と平行に支える静止技。", desc_en: "Planche hold with the legs straddled.", tips_ja: ["肩を強く前傾", "脚を大きく開く", "Tuckから段階的に"], prereqs: ["handstand"], leads: ["planche"] },

  // ─────────── BREAKDANCE 拡張 (13) ───────────
  { id: "indian-step", genre: "break", name_ja: "インディアンステップ", name_en: "Indian Step", lv: 1, tags: ["standing", "basic"], desc_ja: "トップロックの基礎ステップ。", desc_en: "Foundational top rock step.", tips_ja: ["重心を中央に", "肩でビートを取る", "左右対称に踏む"], prereqs: ["toprock"], leads: [] },
  { id: "kick-out", genre: "break", name_ja: "キックアウト", name_en: "Kick Out", lv: 2, tags: ["footwork"], desc_ja: "脚を伸ばして抜くフットワークの繋ぎ。", desc_en: "Footwork transition extending a leg out.", tips_ja: ["手で支えて脚を抜く", "床スレスレに伸ばす", "リズムを保つ"], prereqs: ["6-step"], leads: [] },
  { id: "coffee-grind", genre: "break", name_ja: "コーヒーグラインダー", name_en: "Coffee Grind", lv: 3, tags: ["footwork", "spin"], desc_ja: "片脚を回し他方を跳び越させる回転フットワーク。", desc_en: "Leg-sweep footwork spin (helicopter).", tips_ja: ["片手で支える", "回す脚を低く", "跳ぶ脚のタイミング"], prereqs: ["6-step"], leads: [] },
  { id: "zulu-spin", genre: "break", name_ja: "ズールースピン", name_en: "Zulu Spin", lv: 3, tags: ["footwork", "spin"], desc_ja: "床上で素早く向きを変える回転フットワーク。", desc_en: "Quick rotational footwork spin.", tips_ja: ["手で床を押し回す", "膝を畳む", "視線で回転を制御"], prereqs: ["6-step"], leads: [] },
  { id: "backspin", genre: "break", name_ja: "バックスピン", name_en: "Backspin", lv: 4, tags: ["power", "spin"], desc_ja: "背中を支点に回転するパワームーブ入門。", desc_en: "Spinning on the back — power move basics.", tips_ja: ["脚を抱えて回転半径を小さく", "勢いを腕で作る", "背中の丸い面を使う"], prereqs: ["6-step"], leads: ["windmill"] },
  { id: "1990", genre: "break", name_ja: "ナインティ", name_en: "1990", lv: 8, tags: ["power", "spin", "elite"], desc_ja: "片手倒立で連続回転するパワームーブ。", desc_en: "Continuous one-handed handstand spin.", tips_ja: ["真上で軸を作る", "脚で回転を維持", "手のタップでブースト"], prereqs: ["headspin"], leads: ["2000"] },
  { id: "2000", genre: "break", name_ja: "ニセン", name_en: "2000", lv: 9, tags: ["power", "spin", "elite"], desc_ja: "片手で支え続けて高速回転する1990の上位技。", desc_en: "Sustained one-handed high-speed spin.", tips_ja: ["軸を完全に固める", "肩で支え切る", "回転を絶やさない"], prereqs: ["1990"], leads: [] },
  { id: "jackhammer", genre: "break", name_ja: "ジャックハンマー", name_en: "Jackhammer", lv: 8, tags: ["power", "elite"], desc_ja: "片手で跳ねながら回転するパワームーブ。", desc_en: "Hopping one-handed handstand power move.", tips_ja: ["跳ねるリズムを掴む", "肘を曲げて反発", "回転と跳躍を同期"], prereqs: ["1990"], leads: [] },
  { id: "cricket", genre: "break", name_ja: "クリケット", name_en: "Cricket", lv: 7, tags: ["power"], desc_ja: "両手を交互に跳ねさせて進むパワームーブ。", desc_en: "Hopping on alternating hands.", tips_ja: ["肘で反発を作る", "腰を高く保つ", "左右のリズムを均等に"], prereqs: ["windmill"], leads: ["jackhammer"] },
  { id: "airbaby", genre: "break", name_ja: "エアベイビー", name_en: "Air Baby", lv: 5, tags: ["freeze"], desc_ja: "片手と片膝で体を浮かせて静止するフリーズ。", desc_en: "Freeze balanced on one hand and one knee.", tips_ja: ["肘を膝に固定", "重心を手の上に", "視線で全身を整える"], prereqs: ["baby-freeze"], leads: ["airchair"] },
  { id: "airchair", genre: "break", name_ja: "エアチェア", name_en: "Air Chair", lv: 6, tags: ["freeze"], desc_ja: "片手のみで横向きに体を支えるフリーズ。", desc_en: "Sideways freeze supported on a single hand.", tips_ja: ["肘を骨盤に深く刺す", "脚で形を作る", "肩で押し支える"], prereqs: ["chair-freeze", "airbaby"], leads: [] },
  { id: "hollowback", genre: "break", name_ja: "ホローバック", name_en: "Hollow Back", lv: 7, tags: ["freeze", "strength"], desc_ja: "背中を反らせた倒立姿勢で静止するフリーズ。", desc_en: "Arched handstand freeze.", tips_ja: ["肩の柔軟性を使う", "胸を開く", "腕でしっかり支える"], prereqs: ["handstand"], leads: [] },
  { id: "nike-freeze", genre: "break", name_ja: "ナイキフリーズ", name_en: "Nike Freeze", lv: 4, tags: ["freeze"], desc_ja: "片手と頭で支え脚を斜めに伸ばすフリーズ。", desc_en: "Angled freeze on one hand and the head.", tips_ja: ["肘を腰に当てる", "脚で斜めのラインを作る", "頭と手で三点支持"], prereqs: ["baby-freeze"], leads: [] },

  // ─────────── SKI 拡張 (13) ───────────
  { id: "ski-ollie", genre: "ski", name_ja: "ski オーリー", name_en: "Ski Ollie", lv: 1, tags: ["basic", "air"], desc_ja: "板の反発を使って跳ぶ基礎の飛び出し。", desc_en: "Basic pop using the ski's flex.", tips_ja: ["後方に荷重して反発を使う", "膝を引き上げる", "板を水平に保つ"], prereqs: [], leads: ["ski-180"] },
  { id: "ski-butter", genre: "ski", name_ja: "バター", name_en: "Butter", lv: 2, tags: ["stylish", "basic"], desc_ja: "板の前後を雪面で滑らせるプレス系トリック。", desc_en: "Nose/tail press slid along the snow.", tips_ja: ["片足に荷重を寄せる", "上体でバランスを取る", "ゆっくり戻す"], prereqs: [], leads: [] },
  { id: "ski-900", genre: "ski", name_ja: "ski 900", name_en: "Ski 900", lv: 6, tags: ["spin"], desc_ja: "2回転半のスピン。", desc_en: "Two-and-a-half rotation spin.", tips_ja: ["離陸角度を深く", "腕で回転を絞る", "2回転目で着地を予測"], prereqs: ["ski-720"], leads: ["ski-1080"] },
  { id: "ski-1080", genre: "ski", name_ja: "ski 1080", name_en: "Ski 1080", lv: 7, tags: ["spin"], desc_ja: "3回転のスピン。", desc_en: "Three-rotation aerial spin.", tips_ja: ["高さを最優先", "視線でスポットを取り続ける", "回転中は姿勢を絞る"], prereqs: ["ski-900"], leads: [] },
  { id: "ski-japan", genre: "ski", name_ja: "ジャパングラブ", name_en: "Japan Grab", lv: 4, tags: ["grab"], desc_ja: "後ろ手で板の内側を掴むスタイルグラブ。", desc_en: "Stylish behind-the-back inside grab.", tips_ja: ["膝を深く折る", "上体をひねる", "ホールドを長く"], prereqs: ["ski-mute"], leads: [] },
  { id: "ski-tail", genre: "ski", name_ja: "テールグラブ", name_en: "Tail Grab", lv: 3, tags: ["grab"], desc_ja: "板の後端を掴むグラブ。", desc_en: "Grabbing the tail of the ski.", tips_ja: ["後ろ脚を引き上げる", "上体を倒す", "視線は前へ"], prereqs: [], leads: ["ski-blunt"] },
  { id: "ski-nose", genre: "ski", name_ja: "ノーズグラブ", name_en: "Nose Grab", lv: 3, tags: ["grab"], desc_ja: "板の前端を掴むグラブ。", desc_en: "Grabbing the nose of the ski.", tips_ja: ["前脚を引き上げる", "前傾を保つ", "ホールドを意識"], prereqs: [], leads: [] },
  { id: "ski-blunt", genre: "ski", name_ja: "ブラントグラブ", name_en: "Blunt Grab", lv: 5, tags: ["grab", "stylish"], desc_ja: "後ろ手で板の後方内側を掴む難度の高いグラブ。", desc_en: "Tweaked behind-the-back tail-side grab.", tips_ja: ["体を大きくひねる", "脚を引き付ける", "ホールドで魅せる"], prereqs: ["ski-tail"], leads: [] },
  { id: "ski-critical", genre: "ski", name_ja: "クリティカルグラブ", name_en: "Critical Grab", lv: 5, tags: ["grab"], desc_ja: "両手で板の前方を掴むグラブ。", desc_en: "Two-handed front grab.", tips_ja: ["膝を強く抱える", "両手を同時に", "姿勢を丸める"], prereqs: ["ski-mute"], leads: [] },
  { id: "ski-lincoln", genre: "ski", name_ja: "リンカーンループ", name_en: "Lincoln Loop", lv: 7, tags: ["flip", "off-axis"], desc_ja: "横方向の軸で1回転するオフアクシスフリップ。", desc_en: "Sideways-axis off-axis flip.", tips_ja: ["体を真横に倒す", "肩でリード", "視線で雪面を捉える"], prereqs: ["ski-360"], leads: [] },
  { id: "ski-bio", genre: "ski", name_ja: "バイオ", name_en: "Bio", lv: 8, tags: ["flip", "off-axis"], desc_ja: "前方寄りの斜め軸で回るオフアクシスフリップ。", desc_en: "Forward-leaning off-axis flip.", tips_ja: ["前方へ軸を倒す", "肩で回転を導く", "視線で着地を取る"], prereqs: ["ski-cork-720"], leads: [] },
  { id: "ski-dub-1260", genre: "ski", name_ja: "ダブルコーク1260", name_en: "Double Cork 1260", lv: 9, tags: ["flip", "double", "elite"], desc_ja: "斜め軸で2回フリップしつつ3.5回転する競技必須技。", desc_en: "Double off-axis flip with 1260 of rotation.", tips_ja: ["強い離陸で高さを確保", "回転とフリップを同期", "視線で着地を探し続ける"], prereqs: ["ski-double-cork"], leads: [] },
  { id: "ski-rail-slide", genre: "ski", name_ja: "レールスライド", name_en: "Rail Slide", lv: 4, tags: ["rail"], desc_ja: "レールやボックスを板で滑るジブトリック。", desc_en: "Sliding a rail or box on the skis.", tips_ja: ["板をレールに直角に乗せる", "目線は先へ", "膝で衝撃を吸収"], prereqs: [], leads: [] },

  // ─────────── SNOWBOARD 拡張 (13) ───────────
  { id: "sb-tindy", genre: "snow", name_ja: "ティンディグラブ", name_en: "Tindy Grab", lv: 3, tags: ["grab"], desc_ja: "後ろ手で背中側エッジのつま先寄りを掴むグラブ。", desc_en: "Trailing-hand grab near the heel-edge toe side.", tips_ja: ["脚を引き上げる", "手を短くまとめる", "ホールドを意識"], prereqs: ["sb-indy"], leads: [] },
  { id: "sb-melon", genre: "snow", name_ja: "メロングラブ", name_en: "Melon Grab", lv: 3, tags: ["grab"], desc_ja: "前手で背中側エッジを掴むグラブ。", desc_en: "Front-hand grab on the heel edge.", tips_ja: ["体を背中側にひねる", "膝を抱える", "ホールドを長く"], prereqs: ["sb-ollie"], leads: [] },
  { id: "sb-crail", genre: "snow", name_ja: "クレイルグラブ", name_en: "Crail Grab", lv: 4, tags: ["grab"], desc_ja: "後ろ手で前足側のつま先エッジを掴むグラブ。", desc_en: "Trailing hand grabbing the front-toe edge.", tips_ja: ["前脚を伸ばし気味に", "上体をひねる", "視線は進行方向"], prereqs: ["sb-ollie"], leads: [] },
  { id: "sb-roastbeef", genre: "snow", name_ja: "ローストビーフ", name_en: "Roast Beef", lv: 5, tags: ["grab", "stylish"], desc_ja: "脚の間から後ろ手で背中側エッジを掴むグラブ。", desc_en: "Through-the-legs heel-edge grab.", tips_ja: ["手を脚の間に通す", "体を大きくひねる", "ホールドで魅せる"], prereqs: ["sb-stalefish"], leads: [] },
  { id: "sb-japan", genre: "snow", name_ja: "ジャパングラブ", name_en: "SB Japan Grab", lv: 4, tags: ["grab"], desc_ja: "前手で前足側エッジを掴み体を丸めるグラブ。", desc_en: "Front-hand toe-edge grab with a tucked body.", tips_ja: ["膝を強く抱える", "上体をひねる", "板を真下に保つ"], prereqs: ["sb-mute"], leads: [] },
  { id: "sb-900", genre: "snow", name_ja: "sb 900", name_en: "SB 900", lv: 7, tags: ["spin"], desc_ja: "2回転半のスピン。", desc_en: "Two-and-a-half rotation spin.", tips_ja: ["離陸角度を深く", "腕で回転を絞る", "2回転目で着地を予測"], prereqs: ["sb-720"], leads: ["sb-1080"] },
  { id: "sb-1080", genre: "snow", name_ja: "sb 1080", name_en: "SB 1080", lv: 8, tags: ["spin"], desc_ja: "3回転のスピン。", desc_en: "Three-rotation aerial spin.", tips_ja: ["高さを最優先", "視線でスポットを取る", "回転中は姿勢を絞る"], prereqs: ["sb-900"], leads: [] },
  { id: "sb-cab", genre: "snow", name_ja: "キャブ", name_en: "Cab", lv: 5, tags: ["spin", "switch"], desc_ja: "スイッチスタンスから前方向に回るスピン。", desc_en: "Frontside spin initiated from a switch stance.", tips_ja: ["スイッチの構えを安定させる", "上体でプリセット", "着地でエッジを切り替える"], prereqs: ["sb-360"], leads: [] },
  { id: "sb-wildcat", genre: "snow", name_ja: "ワイルドキャット", name_en: "Wildcat", lv: 6, tags: ["flip", "off-axis"], desc_ja: "横方向の軸で後方に回るフリップ。", desc_en: "Sideways-axis backward flip.", tips_ja: ["体を真横に倒す", "肩でリード", "視線で着地を捉える"], prereqs: ["sb-backflip"], leads: [] },
  { id: "sb-tamedog", genre: "snow", name_ja: "テイムドッグ", name_en: "Tamedog", lv: 6, tags: ["flip", "off-axis"], desc_ja: "横方向の軸で前方に回るフリップ。", desc_en: "Sideways-axis forward flip.", tips_ja: ["前方へ軸を倒す", "膝を抱え込む", "回転後に視線で着地"], prereqs: ["sb-360"], leads: [] },
  { id: "sb-frontflip", genre: "snow", name_ja: "sb フロントフリップ", name_en: "SB Frontflip", lv: 5, tags: ["flip"], desc_ja: "前方宙返り。", desc_en: "Straight front flip on the board.", tips_ja: ["真上に強く跳ぶ", "膝を抱える", "視線で着地を取る"], prereqs: [], leads: ["sb-tamedog"] },
  { id: "sb-boardslide", genre: "snow", name_ja: "ボードスライド", name_en: "Boardslide", lv: 3, tags: ["rail"], desc_ja: "板をレールに直角に乗せて滑るジブトリック。", desc_en: "Sliding a rail with the board across it.", tips_ja: ["板をレールに直角に", "目線は先へ", "膝で吸収"], prereqs: [], leads: ["sb-lipslide"] },
  { id: "sb-lipslide", genre: "snow", name_ja: "リップスライド", name_en: "Lipslide", lv: 4, tags: ["rail"], desc_ja: "後方からレールへ乗り上げて滑るジブトリック。", desc_en: "Approaching the rail from behind into a slide.", tips_ja: ["回し込んでレールに乗せる", "上体を安定させる", "抜けで姿勢を整える"], prereqs: ["sb-boardslide"], leads: [] },
];

export const SKILL_GENRES: SkillGenreDef[] = [
  { id: "all", name_ja: "全て", name_en: "All", abbr: "ALL" },
  { id: "tricking", name_ja: "トリッキング", name_en: "Tricking", abbr: "TRK" },
  { id: "parkour", name_ja: "パルクール", name_en: "Parkour", abbr: "PKR" },
  { id: "gym", name_ja: "体操", name_en: "Gymnastics", abbr: "GYM" },
  { id: "break", name_ja: "ブレイク", name_en: "Breakdance", abbr: "BRK" },
  { id: "ski", name_ja: "スキー", name_en: "Ski", abbr: "SKI" },
  { id: "snow", name_ja: "スノボ", name_en: "Snowboard", abbr: "SNW" },
];
