import { describe, expect, it } from "vitest";
import { contentSecurityPolicy, headerRuleProblems, staticHeaderRules, type HeaderRule } from "./csp";

// public/_headers is generated by scripts/export-static.mjs and applied by Workers Assets
// to the files it serves directly (the prerendered pages, /_next/static/* and public/),
// which bypass headers() in next.config.ts. Pin the rules so a rewrite of the script
// cannot silently drop them.
const page = (path: string, hashes: string[]): HeaderRule => ({
  path,
  headers: [{ key: "Content-Security-Policy", value: contentSecurityPolicy({ scriptHashes: hashes }) }],
});
const rules = staticHeaderRules([page("/", ["sha256-A="]), page("/area/tokyo", ["sha256-B="])]);
const block = (path: string) =>
  (rules.find((r) => r.path === path)?.headers ?? []).map((h) => `${h.key}: ${h.value}`).join("\n");

describe("staticHeaderRules", () => {
  it("caches hashed Next.js assets as immutable", () => {
    expect(block("/_next/static/*")).toContain("Cache-Control: public, max-age=31536000, immutable");
  });

  it("keeps nosniff and the other hardening headers on every file served without the Worker", () => {
    for (const header of ["X-Content-Type-Options: nosniff", "Strict-Transport-Security", "X-Frame-Options: DENY"]) {
      expect(block("/*")).toContain(header);
    }
  });

  it("sets the CSP per path, never in /*, so no path gets two policies", () => {
    expect(block("/*")).not.toContain("Content-Security-Policy");
    expect(block("/")).toContain("'sha256-A='");
    expect(block("/area/tokyo")).toContain("'sha256-B='");
    // Non-HTML files allow no inline script at all.
    expect(block("/favicon.ico")).toContain("script-src 'self' https://static.cloudflareinsights.com;");
  });

  it("serves the extensionless images as PNG", () => {
    for (const path of ["/apple-icon", "/opengraph-image", "/twitter-image"]) {
      expect(block(path)).toContain("Content-Type: image/png");
    }
  });

  it("passes its own checks", () => {
    expect(headerRuleProblems(rules)).toEqual([]);
  });
});

describe("headerRuleProblems", () => {
  it("rejects more than 100 rules", () => {
    const many = Array.from({ length: 101 }, (_, i) => page(`/p${i}`, []));
    expect(headerRuleProblems(many)).toEqual(["101 rules exceed the limit of 100"]);
  });

  it("rejects a line over 2,000 characters", () => {
    const hashes = Array.from({ length: 40 }, (_, i) => `sha256-${"x".repeat(44)}${i}=`);
    expect(headerRuleProblems([page("/", hashes)])[0]).toMatch(/^line over 2,000 characters/);
  });

  it("rejects a path with two rules and a header shared with /*", () => {
    expect(
      headerRuleProblems([
        { path: "/*", headers: [{ key: "X-Frame-Options", value: "DENY" }] },
        page("/", []),
        { path: "/", headers: [{ key: "X-Frame-Options", value: "SAMEORIGIN" }] },
      ]),
    ).toEqual(["/ has more than one rule", "X-Frame-Options is set by both /* and /"]);
  });

  it("accepts rules without a catch-all", () => {
    expect(headerRuleProblems([page("/", [])])).toEqual([]);
  });
});
